//
//  CompanyIdentifier.swift
//  nRFMeshProvision
//
//  Created by Aleksander Nowakowski on 19/06/2019.
//

import Foundation

// Source: https://www.bluetooth.com/specifications/assigned-numbers/company-identifiers/
// Last update date: 19 June 2019
public struct CompanyIdentifier {
    
    private init() {
        // Forbidding instantiating.
    }
    
    public static func name(for id: UInt16) -> String? {
        switch id {
        case 0x0000: return "Ericsson Technology Licensing"
        case 0x0001: return "Nokia Mobile Phones"
        case 0x0002: return "Intel Corp."
        case 0x0003: return "IBM Corp."
        case 0x0004: return "Toshiba Corp."
        case 0x0005: return "3Com"
        case 0x0006: return "Microsoft"
        case 0x0007: return "Lucent"
        case 0x0008: return "Motorola"
        case 0x0009: return "Infineon Technologies AG"
        case 0x000A: return "Qualcomm Technologies International, Ltd. (QTIL)"
        case 0x000B: return "Silicon Wave"
        case 0x000C: return "Digianswer A/S"
        case 0x000D: return "Texas Instruments Inc."
        case 0x000E: return "Parthus Technologies Inc."
        case 0x000F: return "Broadcom Corporation"
        case 0x0010: return "Mitel Semiconductor"
        case 0x0011: return "Widcomm, Inc."
        case 0x0012: return "Zeevo, Inc."
        case 0x0013: return "Atmel Corporation"
        case 0x0014: return "Mitsubishi Electric Corporation"
        case 0x0015: return "RTX Telecom A/S"
        case 0x0016: return "KC Technology Inc."
        case 0x0017: return "Newlogic"
        case 0x0018: return "Transilica, Inc."
        case 0x0019: return "Rohde & Schwarz GmbH & Co. KG"
        case 0x001A: return "TTPCom Limited"
        case 0x001B: return "Signia Technologies, Inc."
        case 0x001C: return "Conexant Systems Inc."
        case 0x001D: return "Qualcomm"
        case 0x001E: return "Inventel"
        case 0x001F: return "AVM Berlin"
        case 0x0020: return "BandSpeed, Inc."
        case 0x0021: return "Mansella Ltd"
        case 0x0022: return "NEC Corporation"
        case 0x0023: return "WavePlus Technology Co., Ltd."
        case 0x0024: return "Alcatel"
        case 0x0025: return "NXP Semiconductors (formerly Philips Semiconductors)"
        case 0x0026: return "C Technologies"
        case 0x0027: return "Open Interface"
        case 0x0028: return "R F Micro Devices"
        case 0x0029: return "Hitachi Ltd"
        case 0x002A: return "Symbol Technologies, Inc."
        case 0x002B: return "Tenovis"
        case 0x002C: return "Macronix International Co. Ltd."
        case 0x002D: return "GCT Semiconductor"
        case 0x002E: return "Norwood Systems"
        case 0x002F: return "MewTel Technology Inc."
        case 0x0030: return "ST Microelectronics"
        case 0x0031: return "Synopsys, Inc."
        case 0x0032: return "Red-M (Communications) Ltd"
        case 0x0033: return "Commil Ltd"
        case 0x0034: return "Computer Access Technology Corporation (CATC)"
        case 0x0035: return "Eclipse (HQ Espana) S.L."
        case 0x0036: return "Renesas Electronics Corporation"
        case 0x0037: return "Mobilian Corporation"
        case 0x0038: return "Syntronix Corporation"
        case 0x0039: return "Integrated System Solution Corp."
        case 0x003A: return "Panasonic Corporation (formerly Matsushita Electric Industrial Co., Ltd.)"
        case 0x003B: return "Gennum Corporation"
        case 0x003C: return "BlackBerry Limited (formerly Research In Motion)"
        case 0x003D: return "IPextreme, Inc."
        case 0x003E: return "Systems and Chips, Inc"
        case 0x003F: return "Bluetooth SIG, Inc"
        case 0x0040: return "Seiko Epson Corporation"
        case 0x0041: return "Integrated Silicon Solution Taiwan, Inc."
        case 0x0042: return "CONWISE Technology Corporation Ltd"
        case 0x0043: return "PARROT AUTOMOTIVE SAS"
        case 0x0044: return "Socket Mobile"
        case 0x0045: return "Atheros Communications, Inc."
        case 0x0046: return "MediaTek, Inc."
        case 0x0047: return "Bluegiga"
        case 0x0048: return "Marvell Technology Group Ltd."
        case 0x0049: return "3DSP Corporation"
        case 0x004A: return "Accel Semiconductor Ltd."
        case 0x004B: return "Continental Automotive Systems"
        case 0x004C: return "Apple, Inc."
        case 0x004D: return "Staccato Communications, Inc."
        case 0x004E: return "Avago Technologies"
        case 0x004F: return "APT Ltd."
        case 0x0050: return "SiRF Technology, Inc."
        case 0x0051: return "Tzero Technologies, Inc."
        case 0x0052: return "J&M Corporation"
        case 0x0053: return "Free2move AB"
        case 0x0054: return "3DiJoy Corporation"
        case 0x0055: return "Plantronics, Inc."
        case 0x0056: return "Sony Ericsson Mobile Communications"
        case 0x0057: return "Harman International Industries, Inc."
        case 0x0058: return "Vizio, Inc."
        case 0x0059: return "Nordic Semiconductor ASA"
        case 0x005A: return "EM Microelectronic-Marin SA"
        case 0x005B: return "Ralink Technology Corporation"
        case 0x005C: return "Belkin International, Inc."
        case 0x005D: return "Realtek Semiconductor Corporation"
        case 0x005E: return "Stonestreet One, LLC"
        case 0x005F: return "Wicentric, Inc."
        case 0x0060: return "RivieraWaves S.A.S"
        case 0x0061: return "RDA Microelectronics"
        case 0x0062: return "Gibson Guitars"
        case 0x0063: return "MiCommand Inc."
        case 0x0064: return "Band XI International, LLC"
        case 0x0065: return "Hewlett-Packard Company"
        case 0x0066: return "9Solutions Oy"
        case 0x0067: return "GN Netcom A/S"
        case 0x0068: return "General Motors"
        case 0x0069: return "A&D Engineering, Inc."
        case 0x006A: return "MindTree Ltd."
        case 0x006B: return "Polar Electro OY"
        case 0x006C: return "Beautiful Enterprise Co., Ltd."
        case 0x006D: return "BriarTek, Inc"
        case 0x006E: return "Summit Data Communications, Inc."
        case 0x006F: return "Sound ID"
        case 0x0070: return "Monster, LLC"
        case 0x0071: return "connectBlue AB"
        case 0x0072: return "ShangHai Super Smart Electronics Co. Ltd."
        case 0x0073: return "Group Sense Ltd."
        case 0x0074: return "Zomm, LLC"
        case 0x0075: return "Samsung Electronics Co. Ltd."
        case 0x0076: return "Creative Technology Ltd."
        case 0x0077: return "Laird Technologies"
        case 0x0078: return "Nike, Inc."
        case 0x0079: return "lesswire AG"
        case 0x007A: return "MStar Semiconductor, Inc."
        case 0x007B: return "Hanlynn Technologies"
        case 0x007C: return "A & R Cambridge"
        case 0x007D: return "Seers Technology Co., Ltd."
        case 0x007E: return "Sports Tracking Technologies Ltd."
        case 0x007F: return "Autonet Mobile"
        case 0x0080: return "DeLorme Publishing Company, Inc."
        case 0x0081: return "WuXi Vimicro"
        case 0x0082: return "Sennheiser Communications A/S"
        case 0x0083: return "TimeKeeping Systems, Inc."
        case 0x0084: return "Ludus Helsinki Ltd."
        case 0x0085: return "BlueRadios, Inc."
        case 0x0086: return "Equinux AG"
        case 0x0087: return "Garmin International, Inc."
        case 0x0088: return "Ecotest"
        case 0x0089: return "GN ReSound A/S"
        case 0x008A: return "Jawbone"
        case 0x008B: return "Topcon Positioning Systems, LLC"
        case 0x008C: return "Gimbal Inc. (formerly Qualcomm Labs, Inc. and Qualcomm Retail Solutions, Inc.)"
        case 0x008D: return "Zscan Software"
        case 0x008E: return "Quintic Corp"
        case 0x008F: return "Telit Wireless Solutions GmbH (formerly Stollmann E+V GmbH)"
        case 0x0090: return "Funai Electric Co., Ltd."
        case 0x0091: return "Advanced PANMOBIL systems GmbH & Co. KG"
        case 0x0092: return "ThinkOptics, Inc."
        case 0x0093: return "Universal Electronics, Inc."
        case 0x0094: return "Airoha Technology Corp."
        case 0x0095: return "NEC Lighting, Ltd."
        case 0x0096: return "ODM Technology, Inc."
        case 0x0097: return "ConnecteDevice Ltd."
        case 0x0098: return "zero1.tv GmbH"
        case 0x0099: return "i.Tech Dynamic Global Distribution Ltd."
        case 0x009A: return "Alpwise"
        case 0x009B: return "Jiangsu Toppower Automotive Electronics Co., Ltd."
        case 0x009C: return "Colorfy, Inc."
        case 0x009D: return "Geoforce Inc."
        case 0x009E: return "Bose Corporation"
        case 0x009F: return "Suunto Oy"
        case 0x00A0: return "Kensington Computer Products Group"
        case 0x00A1: return "SR-Medizinelektronik"
        case 0x00A2: return "Vertu Corporation Limited"
        case 0x00A3: return "Meta Watch Ltd."
        case 0x00A4: return "LINAK A/S"
        case 0x00A5: return "OTL Dynamics LLC"
        case 0x00A6: return "Panda Ocean Inc."
        case 0x00A7: return "Visteon Corporation"
        case 0x00A8: return "ARP Devices Limited"
        case 0x00A9: return "Magneti Marelli S.p.A"
        case 0x00AA: return "CAEN RFID srl"
        case 0x00AB: return "Ingenieur-Systemgruppe Zahn GmbH"
        case 0x00AC: return "Green Throttle Games"
        case 0x00AD: return "Peter Systemtechnik GmbH"
        case 0x00AE: return "Omegawave Oy"
        case 0x00AF: return "Cinetix"
        case 0x00B0: return "Passif Semiconductor Corp"
        case 0x00B1: return "Saris Cycling Group, Inc"
        case 0x00B2: return "Bekey A/S"
        case 0x00B3: return "Clarinox Technologies Pty. Ltd."
        case 0x00B4: return "BDE Technology Co., Ltd."
        case 0x00B5: return "Swirl Networks"
        case 0x00B6: return "Meso international"
        case 0x00B7: return "TreLab Ltd"
        case 0x00B8: return "Qualcomm Innovation Center, Inc. (QuIC)"
        case 0x00B9: return "Johnson Controls, Inc."
        case 0x00BA: return "Starkey Laboratories Inc."
        case 0x00BB: return "S-Power Electronics Limited"
        case 0x00BC: return "Ace Sensor Inc"
        case 0x00BD: return "Aplix Corporation"
        case 0x00BE: return "AAMP of America"
        case 0x00BF: return "Stalmart Technology Limited"
        case 0x00C0: return "AMICCOM Electronics Corporation"
        case 0x00C1: return "Shenzhen Excelsecu Data Technology Co.,Ltd"
        case 0x00C2: return "Geneq Inc."
        case 0x00C3: return "Adidas AG"
        case 0x00C4: return "LG Electronics?"
        case 0x00C5: return "Onset Computer Corporation"
        case 0x00C6: return "Selfly BV"
        case 0x00C7: return "Quuppa Oy."
        case 0x00C8: return "GeLo Inc"
        case 0x00C9: return "Evluma"
        case 0x00CA: return "MC10"
        case 0x00CB: return "Binauric SE"
        case 0x00CC: return "Beats Electronics"
        case 0x00CD: return "Microchip Technology Inc."
        case 0x00CE: return "Elgato Systems GmbH"
        case 0x00CF: return "ARCHOS SA"
        case 0x00D0: return "Dexcom, Inc."
        case 0x00D1: return "Polar Electro Europe B.V."
        case 0x00D2: return "Dialog Semiconductor B.V."
        case 0x00D3: return "Taixingbang Technology (HK) Co,. LTD."
        case 0x00D4: return "Kawantech"
        case 0x00D5: return "Austco Communication Systems"
        case 0x00D6: return "Timex Group USA, Inc."
        case 0x00D7: return "Qualcomm Technologies, Inc."
        case 0x00D8: return "Qualcomm Connected Experiences, Inc."
        case 0x00D9: return "Voyetra Turtle Beach"
        case 0x00DA: return "txtr GmbH"
        case 0x00DB: return "Biosentronics"
        case 0x00DC: return "Procter & Gamble"
        case 0x00DD: return "Hosiden Corporation"
        case 0x00DE: return "Muzik LLC"
        case 0x00DF: return "Misfit Wearables Corp"
        case 0x00E0: return "Google"
        case 0x00E1: return "Danlers Ltd"
        case 0x00E2: return "Semilink Inc"
        case 0x00E3: return "inMusic Brands, Inc"
        case 0x00E4: return "L.S. Research Inc."
        case 0x00E5: return "Eden Software Consultants Ltd."
        case 0x00E6: return "Freshtemp"
        case 0x00E7: return "KS Technologies"
        case 0x00E8: return "ACTS Technologies"
        case 0x00E9: return "Vtrack Systems"
        case 0x00EA: return "Nielsen-Kellerman Company"
        case 0x00EB: return "Server Technology Inc."
        case 0x00EC: return "BioResearch Associates"
        case 0x00ED: return "Jolly Logic, LLC"
        case 0x00EE: return "Above Average Outcomes, Inc."
        case 0x00EF: return "Bitsplitters GmbH"
        case 0x00F0: return "PayPal, Inc."
        case 0x00F1: return "Witron Technology Limited"
        case 0x00F2: return "Morse Project Inc."
        case 0x00F3: return "Kent Displays Inc."
        case 0x00F4: return "Nautilus Inc."
        case 0x00F5: return "Smartifier Oy"
        case 0x00F6: return "Elcometer Limited"
        case 0x00F7: return "VSN Technologies, Inc."
        case 0x00F8: return "AceUni Corp., Ltd."
        case 0x00F9: return "StickNFind"
        case 0x00FA: return "Crystal Code AB"
        case 0x00FB: return "KOUKAAM a.s."
        case 0x00FC: return "Delphi Corporation"
        case 0x00FD: return "ValenceTech Limited"
        case 0x00FE: return "Stanley Black and Decker"
        case 0x00FF: return "Typo Products, LLC"
        case 0x0100: return "TomTom International BV"
        case 0x0101: return "Fugoo, Inc."
        case 0x0102: return "Keiser Corporation"
        case 0x0103: return "Bang & Olufsen A/S"
        case 0x0104: return "PLUS Location Systems Pty Ltd"
        case 0x0105: return "Ubiquitous Computing Technology Corporation"
        case 0x0106: return "Innovative Yachtter Solutions"
        case 0x0107: return "William Demant Holding A/S"
        case 0x0108: return "Chicony Electronics Co., Ltd."
        case 0x0109: return "Atus BV"
        case 0x010A: return "Codegate Ltd"
        case 0x010B: return "ERi, Inc"
        case 0x010C: return "Transducers Direct, LLC"
        case 0x010D: return "DENSO TEN LIMITED (formerly Fujitsu Ten LImited)"
        case 0x010E: return "Audi AG"
        case 0x010F: return "HiSilicon Technologies Col, Ltd."
        case 0x0110: return "Nippon Seiki Co., Ltd."
        case 0x0111: return "Steelseries ApS"
        case 0x0112: return "Visybl Inc."
        case 0x0113: return "Openbrain Technologies, Co., Ltd."
        case 0x0114: return "Xensr"
        case 0x0115: return "e.solutions"
        case 0x0116: return "10AK Technologies"
        case 0x0117: return "Wimoto Technologies Inc"
        case 0x0118: return "Radius Networks, Inc."
        case 0x0119: return "Wize Technology Co., Ltd."
        case 0x011A: return "Qualcomm Labs, Inc."
        case 0x011B: return "Hewlett Packard Enterprise"
        case 0x011C: return "Baidu"
        case 0x011D: return "Arendi AG"
        case 0x011E: return "Skoda Auto a.s."
        case 0x011F: return "Volkswagen AG"
        case 0x0120: return "Porsche AG"
        case 0x0121: return "Sino Wealth Electronic Ltd."
        case 0x0122: return "AirTurn, Inc."
        case 0x0123: return "Kinsa, Inc"
        case 0x0124: return "HID Global"
        case 0x0125: return "SEAT es"
        case 0x0126: return "Promethean Ltd."
        case 0x0127: return "Salutica Allied Solutions"
        case 0x0128: return "GPSI Group Pty Ltd"
        case 0x0129: return "Nimble Devices Oy"
        case 0x012A: return "Changzhou Yongse Infotech Co., Ltd."
        case 0x012B: return "SportIQ"
        case 0x012C: return "TEMEC Instruments B.V."
        case 0x012D: return "Sony Corporation"
        case 0x012E: return "ASSA ABLOY"
        case 0x012F: return "Clarion Co. Inc."
        case 0x0130: return "Warehouse Innovations"
        case 0x0131: return "Cypress Semiconductor"
        case 0x0132: return "MADS Inc"
        case 0x0133: return "Blue Maestro Limited"
        case 0x0134: return "Resolution Products, Ltd."
        case 0x0135: return "Aireware LLC"
        case 0x0136: return "Silvair, Inc."
        case 0x0137: return "Prestigio Plaza Ltd."
        case 0x0138: return "NTEO Inc."
        case 0x0139: return "Focus Systems Corporation"
        case 0x013A: return "Tencent Holdings Ltd."
        case 0x013B: return "Allegion"
        case 0x013C: return "Murata Manufacturing Co., Ltd."
        case 0x013D: return "WirelessWERX"
        case 0x013E: return "Nod, Inc."
        case 0x013F: return "B&B Manufacturing Company"
        case 0x0140: return "Alpine Electronics (China) Co., Ltd"
        case 0x0141: return "FedEx Services"
        case 0x0142: return "Grape Systems Inc."
        case 0x0143: return "Bkon Connect"
        case 0x0144: return "Lintech GmbH"
        case 0x0145: return "Novatel Wireless"
        case 0x0146: return "Ciright"
        case 0x0147: return "Mighty Cast, Inc."
        case 0x0148: return "Ambimat Electronics"
        case 0x0149: return "Perytons Ltd."
        case 0x014A: return "Tivoli Audio, LLC"
        case 0x014B: return "Master Lock"
        case 0x014C: return "Mesh-Net Ltd"
        case 0x014D: return "HUIZHOU DESAY SV AUTOMOTIVE CO., LTD."
        case 0x014E: return "Tangerine, Inc."
        case 0x014F: return "B&W Group Ltd."
        case 0x0150: return "Pioneer Corporation"
        case 0x0151: return "OnBeep"
        case 0x0152: return "Vernier Software & Technology"
        case 0x0153: return "ROL Ergo"
        case 0x0154: return "Pebble Technology"
        case 0x0155: return "NETATMO"
        case 0x0156: return "Accumulate AB"
        case 0x0157: return "Anhui Huami Information Technology Co., Ltd."
        case 0x0158: return "Inmite s.r.o."
        case 0x0159: return "ChefSteps, Inc."
        case 0x015A: return "micas AG"
        case 0x015B: return "Biomedical Research Ltd."
        case 0x015C: return "Pitius Tec S.L."
        case 0x015D: return "Estimote, Inc."
        case 0x015E: return "Unikey Technologies, Inc."
        case 0x015F: return "Timer Cap Co."
        case 0x0160: return "AwoX"
        case 0x0161: return "yikes"
        case 0x0162: return "MADSGlobalNZ Ltd."
        case 0x0163: return "PCH International"
        case 0x0164: return "Qingdao Yeelink Information Technology Co., Ltd."
        case 0x0165: return "Milwaukee Tool (Formally Milwaukee Electric Tools)"
        case 0x0166: return "MISHIK Pte Ltd"
        case 0x0167: return "Ascensia Diabetes Care US Inc."
        case 0x0168: return "Spicebox LLC"
        case 0x0169: return "emberlight"
        case 0x016A: return "Cooper-Atkins Corporation"
        case 0x016B: return "Qblinks"
        case 0x016C: return "MYSPHERA"
        case 0x016D: return "LifeScan Inc"
        case 0x016E: return "Volantic AB"
        case 0x016F: return "Podo Labs, Inc"
        case 0x0170: return "Roche Diabetes Care AG"
        case 0x0171: return "Amazon Fulfillment Service"
        case 0x0172: return "Connovate Technology Private Limited"
        case 0x0173: return "Kocomojo, LLC"
        case 0x0174: return "Everykey Inc."
        case 0x0175: return "Dynamic Controls"
        case 0x0176: return "SentriLock"
        case 0x0177: return "I-SYST inc."
        case 0x0178: return "CASIO COMPUTER CO., LTD."
        case 0x0179: return "LAPIS Semiconductor Co., Ltd."
        case 0x017A: return "Telemonitor, Inc."
        case 0x017B: return "taskit GmbH"
        case 0x017C: return "Daimler AG"
        case 0x017D: return "BatAndCat"
        case 0x017E: return "BluDotz Ltd"
        case 0x017F: return "XTel Wireless ApS"
        case 0x0180: return "Gigaset Communications GmbH"
        case 0x0181: return "Gecko Health Innovations, Inc."
        case 0x0182: return "HOP Ubiquitous"
        case 0x0183: return "Walt Disney"
        case 0x0184: return "Nectar"
        case 0x0185: return "bel'apps LLC"
        case 0x0186: return "CORE Lighting Ltd"
        case 0x0187: return "Seraphim Sense Ltd"
        case 0x0188: return "Unico RBC"
        case 0x0189: return "Physical Enterprises Inc."
        case 0x018A: return "Able Trend Technology Limited"
        case 0x018B: return "Konica Minolta, Inc."
        case 0x018C: return "Wilo SE"
        case 0x018D: return "Extron Design Services"
        case 0x018E: return "Fitbit, Inc."
        case 0x018F: return "Fireflies Systems"
        case 0x0190: return "Intelletto Technologies Inc."
        case 0x0191: return "FDK CORPORATION"
        case 0x0192: return "Cloudleaf, Inc"
        case 0x0193: return "Maveric Automation LLC"
        case 0x0194: return "Acoustic Stream Corporation"
        case 0x0195: return "Zuli"
        case 0x0196: return "Paxton Access Ltd"
        case 0x0197: return "WiSilica Inc."
        case 0x0198: return "VENGIT Korlatolt Felelossegu Tarsasag"
        case 0x0199: return "SALTO SYSTEMS S.L."
        case 0x019A: return "TRON Forum (formerly T-Engine Forum)"
        case 0x019B: return "CUBETECH s.r.o."
        case 0x019C: return "Cokiya Incorporated"
        case 0x019D: return "CVS Health"
        case 0x019E: return "Ceruus"
        case 0x019F: return "Strainstall Ltd"
        case 0x01A0: return "Channel Enterprises (HK) Ltd."
        case 0x01A1: return "FIAMM"
        case 0x01A2: return "GIGALANE.CO.,LTD"
        case 0x01A3: return "EROAD"
        case 0x01A4: return "Mine Safety Appliances"
        case 0x01A5: return "Icon Health and Fitness"
        case 0x01A6: return "Wille Engineering (formely as Asandoo GmbH)"
        case 0x01A7: return "ENERGOUS CORPORATION"
        case 0x01A8: return "Taobao"
        case 0x01A9: return "Canon Inc."
        case 0x01AA: return "Geophysical Technology Inc."
        case 0x01AB: return "Facebook, Inc."
        case 0x01AC: return "Trividia Health, Inc."
        case 0x01AD: return "FlightSafety International"
        case 0x01AE: return "Earlens Corporation"
        case 0x01AF: return "Sunrise Micro Devices, Inc."
        case 0x01B0: return "Star Micronics Co., Ltd."
        case 0x01B1: return "Netizens Sp. z o.o."
        case 0x01B2: return "Nymi Inc."
        case 0x01B3: return "Nytec, Inc."
        case 0x01B4: return "Trineo Sp. z o.o."
        case 0x01B5: return "Nest Labs Inc."
        case 0x01B6: return "LM Technologies Ltd"
        case 0x01B7: return "General Electric Company"
        case 0x01B8: return "i+D3 S.L."
        case 0x01B9: return "HANA Micron"
        case 0x01BA: return "Stages Cycling LLC"
        case 0x01BB: return "Cochlear Bone Anchored Solutions AB"
        case 0x01BC: return "SenionLab AB"
        case 0x01BD: return "Syszone Co., Ltd"
        case 0x01BE: return "Pulsate Mobile Ltd."
        case 0x01BF: return "Hong Kong HunterSun Electronic Limited"
        case 0x01C0: return "pironex GmbH"
        case 0x01C1: return "BRADATECH Corp."
        case 0x01C2: return "Transenergooil AG"
        case 0x01C3: return "Bunch"
        case 0x01C4: return "DME Microelectronics"
        case 0x01C5: return "Bitcraze AB"
        case 0x01C6: return "HASWARE Inc."
        case 0x01C7: return "Abiogenix Inc."
        case 0x01C8: return "Poly-Control ApS"
        case 0x01C9: return "Avi-on"
        case 0x01CA: return "Laerdal Medical AS"
        case 0x01CB: return "Fetch My Pet"
        case 0x01CC: return "Sam Labs Ltd."
        case 0x01CD: return "Chengdu Synwing Technology Ltd"
        case 0x01CE: return "HOUWA SYSTEM DESIGN, k.k."
        case 0x01CF: return "BSH"
        case 0x01D0: return "Primus Inter Pares Ltd"
        case 0x01D1: return "August Home, Inc"
        case 0x01D2: return "Gill Electronics"
        case 0x01D3: return "Sky Wave Design"
        case 0x01D4: return "Newlab S.r.l."
        case 0x01D5: return "ELAD srl"
        case 0x01D6: return "G-wearables inc."
        case 0x01D7: return "Squadrone Systems Inc."
        case 0x01D8: return "Code Corporation"
        case 0x01D9: return "Savant Systems LLC"
        case 0x01DA: return "Logitech International SA"
        case 0x01DB: return "Innblue Consulting"
        case 0x01DC: return "iParking Ltd."
        case 0x01DD: return "Koninklijke Philips Electronics N.V."
        case 0x01DE: return "Minelab Electronics Pty Limited"
        case 0x01DF: return "Bison Group Ltd."
        case 0x01E0: return "Widex A/S"
        case 0x01E1: return "Jolla Ltd"
        case 0x01E2: return "Lectronix, Inc."
        case 0x01E3: return "Caterpillar Inc"
        case 0x01E4: return "Freedom Innovations"
        case 0x01E5: return "Dynamic Devices Ltd"
        case 0x01E6: return "Technology Solutions (UK) Ltd"
        case 0x01E7: return "IPS Group Inc."
        case 0x01E8: return "STIR"
        case 0x01E9: return "Sano, Inc."
        case 0x01EA: return "Advanced Application Design, Inc."
        case 0x01EB: return "AutoMap LLC"
        case 0x01EC: return "Spreadtrum Communications Shanghai Ltd"
        case 0x01ED: return "CuteCircuit LTD"
        case 0x01EE: return "Valeo Service"
        case 0x01EF: return "Fullpower Technologies, Inc."
        case 0x01F0: return "KloudNation"
        case 0x01F1: return "Zebra Technologies Corporation"
        case 0x01F2: return "Itron, Inc."
        case 0x01F3: return "The University of Tokyo"
        case 0x01F4: return "UTC Fire and Security"
        case 0x01F5: return "Cool Webthings Limited"
        case 0x01F6: return "DJO Global"
        case 0x01F7: return "Gelliner Limited"
        case 0x01F8: return "Anyka (Guangzhou) Microelectronics Technology Co, LTD"
        case 0x01F9: return "Medtronic Inc."
        case 0x01FA: return "Gozio Inc."
        case 0x01FB: return "Form Lifting, LLC"
        case 0x01FC: return "Wahoo Fitness, LLC"
        case 0x01FD: return "Kontakt Micro-Location Sp. z o.o."
        case 0x01FE: return "Radio Systems Corporation"
        case 0x01FF: return "Freescale Semiconductor, Inc."
        case 0x0200: return "Verifone Systems Pte Ltd. Taiwan Branch"
        case 0x0201: return "AR Timing"
        case 0x0202: return "Rigado LLC"
        case 0x0203: return "Kemppi Oy"
        case 0x0204: return "Tapcentive Inc."
        case 0x0205: return "Smartbotics Inc."
        case 0x0206: return "Otter Products, LLC"
        case 0x0207: return "STEMP Inc."
        case 0x0208: return "LumiGeek LLC"
        case 0x0209: return "InvisionHeart Inc."
        case 0x020A: return "Macnica Inc."
        case 0x020B: return "Jaguar Land Rover Limited"
        case 0x020C: return "CoroWare Technologies, Inc"
        case 0x020D: return "Simplo Technology Co., LTD"
        case 0x020E: return "Omron Healthcare Co., LTD"
        case 0x020F: return "Comodule GMBH"
        case 0x0210: return "ikeGPS"
        case 0x0211: return "Telink Semiconductor Co. Ltd"
        case 0x0212: return "Interplan Co., Ltd"
        case 0x0213: return "Wyler AG"
        case 0x0214: return "IK Multimedia Production srl"
        case 0x0215: return "Lukoton Experience Oy"
        case 0x0216: return "MTI Ltd"
        case 0x0217: return "Tech4home, Lda"
        case 0x0218: return "Hiotech AB"
        case 0x0219: return "DOTT Limited"
        case 0x021A: return "Blue Speck Labs, LLC"
        case 0x021B: return "Cisco Systems, Inc"
        case 0x021C: return "Mobicomm Inc"
        case 0x021D: return "Edamic"
        case 0x021E: return "Goodnet, Ltd"
        case 0x021F: return "Luster Leaf Products Inc"
        case 0x0220: return "Manus Machina BV"
        case 0x0221: return "Mobiquity Networks Inc"
        case 0x0222: return "Praxis Dynamics"
        case 0x0223: return "Philip Morris Products S.A."
        case 0x0224: return "Comarch SA"
        case 0x0226: return "Merlinia A/S"
        case 0x0227: return "LifeBEAM Technologies"
        case 0x0228: return "Twocanoes Labs, LLC"
        case 0x0229: return "Muoverti Limited"
        case 0x022A: return "Stamer Musikanlagen GMBH"
        case 0x022B: return "Tesla Motors"
        case 0x022C: return "Pharynks Corporation"
        case 0x022D: return "Lupine"
        case 0x022E: return "Siemens AG"
        case 0x022F: return "Huami (Shanghai) Culture Communication CO., LTD"
        case 0x0230: return "Foster Electric Company, Ltd"
        case 0x0231: return "ETA SA"
        case 0x0232: return "x-Senso Solutions Kft"
        case 0x0233: return "Shenzhen SuLong Communication Ltd"
        case 0x0234: return "FengFan (BeiJing) Technology Co, Ltd"
        case 0x0235: return "Qrio Inc"
        case 0x0236: return "Pitpatpet Ltd"
        case 0x0237: return "MSHeli s.r.l."
        case 0x0238: return "Trakm8 Ltd"
        case 0x0239: return "JIN CO, Ltd"
        case 0x023A: return "Alatech Tehnology"
        case 0x023B: return "Beijing CarePulse Electronic Technology Co, Ltd"
        case 0x023C: return "Awarepoint"
        case 0x023D: return "ViCentra B.V."
        case 0x023E: return "Raven Industries"
        case 0x023F: return "WaveWare Technologies Inc."
        case 0x0240: return "Argenox Technologies"
        case 0x0241: return "Bragi GmbH"
        case 0x0242: return "16Lab Inc"
        case 0x0243: return "Masimo Corp"
        case 0x0244: return "Iotera Inc"
        case 0x0246: return "ACKme Networks, Inc."
        case 0x0247: return "FiftyThree Inc."
        case 0x0248: return "Parker Hannifin Corp"
        case 0x0249: return "Transcranial Ltd"
        case 0x024A: return "Uwatec AG"
        case 0x024B: return "Orlan LLC"
        case 0x024C: return "Blue Clover Devices"
        case 0x024D: return "M-Way Solutions GmbH"
        case 0x024E: return "Microtronics Engineering GmbH"
        case 0x0250: return "Sapphire Circuits LLC"
        case 0x0251: return "Lumo Bodytech Inc."
        case 0x0252: return "UKC Technosolution"
        case 0x0253: return "Xicato Inc."
        case 0x0254: return "Playbrush"
        case 0x0255: return "Dai Nippon Printing Co., Ltd."
        case 0x0256: return "G24 Power Limited"
        case 0x0257: return "AdBabble Local Commerce Inc."
        case 0x0258: return "Devialet SA"
        case 0x0259: return "ALTYOR"
        case 0x025A: return "University of Applied Sciences Valais/Haute Ecole Valaisanne"
        case 0x025B: return "Five Interactive, LLC dba Zendo"
        case 0x025C: return "NetEase Hangzhou Network co.Ltd."
        case 0x025D: return "Lexmark International Inc."
        case 0x025E: return "Fluke Corporation"
        case 0x025F: return "Yardarm Technologies"
        case 0x0260: return "SensaRx"
        case 0x0261: return "SECVRE GmbH"
        case 0x0262: return "Glacial Ridge Technologies"
        case 0x0263: return "Identiv, Inc."
        case 0x0264: return "DDS, Inc."
        case 0x0265: return "SMK Corporation"
        case 0x0266: return "Schawbel Technologies LLC"
        case 0x0267: return "XMI Systems SA"
        case 0x0268: return "Cerevo"
        case 0x0269: return "Torrox GmbH & Co KG"
        case 0x026A: return "Gemalto"
        case 0x026B: return "DEKA Research & Development Corp."
        case 0x026C: return "Domster Tadeusz Szydlowski"
        case 0x026D: return "Technogym SPA"
        case 0x026E: return "FLEURBAEY BVBA"
        case 0x026F: return "Aptcode Solutions"
        case 0x0270: return "LSI ADL Technology"
        case 0x0271: return "Animas Corp"
        case 0x0272: return "Alps Electric Co., Ltd."
        case 0x0273: return "OCEASOFT"
        case 0x0274: return "Motsai Research"
        case 0x0275: return "Geotab"
        case 0x0276: return "E.G.O. Elektro-Geratebau GmbH"
        case 0x0277: return "bewhere inc"
        case 0x0278: return "Johnson Outdoors Inc"
        case 0x0279: return "steute Schaltgerate GmbH & Co. KG"
        case 0x027A: return "Ekomini inc."
        case 0x027B: return "DEFA AS"
        case 0x027C: return "Aseptika Ltd"
        case 0x027D: return "HUAWEI Technologies Co., Ltd."
        case 0x027E: return "HabitAware, LLC"
        case 0x027F: return "ruwido austria gmbh"
        case 0x0280: return "ITEC corporation"
        case 0x0281: return "StoneL"
        case 0x0282: return "Sonova AG"
        case 0x0283: return "Maven Machines, Inc."
        case 0x0284: return "Synapse Electronics"
        case 0x0285: return "Standard Innovation Inc."
        case 0x0286: return "RF Code, Inc."
        case 0x0287: return "Wally Ventures S.L."
        case 0x0288: return "Willowbank Electronics Ltd"
        case 0x0289: return "SK Telecom"
        case 0x028A: return "Jetro AS"
        case 0x028B: return "Code Gears LTD"
        case 0x028C: return "NANOLINK APS"
        case 0x028D: return "IF, LLC"
        case 0x028E: return "RF Digital Corp"
        case 0x028F: return "Church & Dwight Co., Inc"
        case 0x0290: return "Multibit Oy"
        case 0x0291: return "CliniCloud Inc"
        case 0x0292: return "SwiftSensors"
        case 0x0293: return "Blue Bite"
        case 0x0294: return "ELIAS GmbH"
        case 0x0295: return "Sivantos GmbH"
        case 0x0296: return "Petzl"
        case 0x0297: return "storm power ltd"
        case 0x0298: return "EISST Ltd"
        case 0x0299: return "Inexess Technology Simma KG"
        case 0x029A: return "Currant, Inc."
        case 0x029B: return "C2 Development, Inc."
        case 0x029C: return "Blue Sky Scientific, LLC"
        case 0x029D: return "ALOTTAZS LABS, LLC"
        case 0x029E: return "Kupson spol. s r.o."
        case 0x029F: return "Areus Engineering GmbH"
        case 0x02A0: return "Impossible Camera GmbH"
        case 0x02A1: return "InventureTrack Systems"
        case 0x02A2: return "LockedUp"
        case 0x02A3: return "Itude"
        case 0x02A4: return "Pacific Lock Company"
        case 0x02A5: return "Tendyron Corporation ( ??????????? )"
        case 0x02A6: return "Robert Bosch GmbH"
        case 0x02A7: return "Illuxtron international B.V."
        case 0x02A8: return "miSport Ltd."
        case 0x02A9: return "Chargelib"
        case 0x02AA: return "Doppler Lab"
        case 0x02AB: return "BBPOS Limited"
        case 0x02AC: return "RTB Elektronik GmbH & Co. KG"
        case 0x02AD: return "Rx Networks, Inc."
        case 0x02AE: return "WeatherFlow, Inc."
        case 0x02AF: return "Technicolor USA Inc."
        case 0x02B0: return "Bestechnic(Shanghai),Ltd"
        case 0x02B1: return "Raden Inc"
        case 0x02B2: return "JouZen Oy"
        case 0x02B3: return "CLABER S.P.A."
        case 0x02B4: return "Hyginex, Inc."
        case 0x02B5: return "HANSHIN ELECTRIC RAILWAY CO.,LTD."
        case 0x02B6: return "Schneider Electric"
        case 0x02B7: return "Oort Technologies LLC"
        case 0x02B8: return "Chrono Therapeutics"
        case 0x02B9: return "Rinnai Corporation"
        case 0x02BA: return "Swissprime Technologies AG"
        case 0x02BB: return "Koha.,Co.Ltd"
        case 0x02BC: return "Genevac Ltd"
        case 0x02BD: return "Chemtronics"
        case 0x02BE: return "Seguro Technology Sp. z o.o."
        case 0x02BF: return "Redbird Flight Simulations"
        case 0x02C0: return "Dash Robotics"
        case 0x02C1: return "LINE Corporation"
        case 0x02C2: return "Guillemot Corporation"
        case 0x02C3: return "Techtronic Power Tools Technology Limited"
        case 0x02C4: return "Wilson Sporting Goods"
        case 0x02C5: return "Lenovo (Singapore) Pte Ltd."
        case 0x02C6: return "Ayatan Sensors"
        case 0x02C7: return "Electronics Tomorrow Limited"
        case 0x02C8: return "VASCO Data Security International, Inc."
        case 0x02C9: return "PayRange Inc."
        case 0x02CA: return "ABOV Semiconductor"
        case 0x02CB: return "AINA-Wireless Inc."
        case 0x02CC: return "Eijkelkamp Soil & Water"
        case 0x02CD: return "BMA ergonomics b.v."
        case 0x02CE: return "Teva Branded Pharmaceutical Products R&D, Inc."
        case 0x02CF: return "Anima"
        case 0x02D0: return "3M"
        case 0x02D1: return "Empatica Srl"
        case 0x02D2: return "Afero, Inc."
        case 0x02D3: return "Powercast Corporation"
        case 0x02D4: return "Secuyou ApS"
        case 0x02D5: return "OMRON Corporation"
        case 0x02D6: return "Send Solutions"
        case 0x02D7: return "NIPPON SYSTEMWARE CO.,LTD."
        case 0x02D8: return "Neosfar"
        case 0x02D9: return "Fliegl Agrartechnik GmbH"
        case 0x02DA: return "Gilvader"
        case 0x02DB: return "Digi International Inc (R)"
        case 0x02DC: return "DeWalch Technologies, Inc."
        case 0x02DD: return "Flint Rehabilitation Devices, LLC"
        case 0x02DE: return "Samsung SDS Co., Ltd."
        case 0x02DF: return "Blur Product Development"
        case 0x02E0: return "University of Michigan"
        case 0x02E1: return "Victron Energy BV"
        case 0x02E2: return "NTT docomo"
        case 0x02E3: return "Carmanah Technologies Corp."
        case 0x02E4: return "Bytestorm Ltd."
        case 0x02E5: return "Espressif Incorporated"
        case 0x02E6: return "Unwire"
        case 0x02E7: return "Connected Yard, Inc."
        case 0x02E8: return "American Music Environments"
        case 0x02E9: return "Sensogram Technologies, Inc."
        case 0x02EA: return "Fujitsu Limited"
        case 0x02EB: return "Ardic Technology"
        case 0x02EC: return "Delta Systems, Inc"
        case 0x02EF: return "SMART-INNOVATION.inc"
        case 0x02F1: return "The Idea Cave, LLC"
        case 0x02F2: return "GoPro, Inc."
        case 0x02F3: return "AuthAir, Inc"
        case 0x02F4: return "Vensi, Inc."
        case 0x02F5: return "Indagem Tech LLC"
        case 0x02F6: return "Intemo Technologies"
        case 0x02F7: return "DreamVisions co., Ltd."
        case 0x02F8: return "Runteq Oy Ltd"
        case 0x02FA: return "CoSTAR TEchnologies"
        case 0x02FB: return "Clarius Mobile Health Corp."
        case 0x02FC: return "Shanghai Frequen Microelectronics Co., Ltd."
        case 0x02FD: return "Uwanna, Inc."
        case 0x02FE: return "Lierda Science & Technology Group Co., Ltd."
        case 0x02FF: return "Silicon Laboratories"
        case 0x0300: return "World Moto Inc."
        case 0x0301: return "Giatec Scientific Inc."
        case 0x0302: return "Loop Devices, Inc"
        case 0x0303: return "IACA electronique"
        case 0x0304: return "Proxy Technologies, Inc."
        case 0x0305: return "Swipp ApS"
        case 0x0307: return "FUJI INDUSTRIAL CO.,LTD."
        case 0x0308: return "Surefire, LLC"
        case 0x0309: return "Dolby Labs"
        case 0x030A: return "Ellisys"
        case 0x030B: return "Magnitude Lighting Converters"
        case 0x030C: return "Hilti AG"
        case 0x030D: return "Devdata S.r.l."
        case 0x030E: return "Deviceworx"
        case 0x030F: return "Shortcut Labs"
        case 0x0310: return "SGL Italia S.r.l."
        case 0x0311: return "PEEQ DATA"
        case 0x0314: return "RIIG AI Sp. z o.o."
        case 0x031E: return "Eyefi, Inc."
        case 0x0328: return "Grundfos A/S"
        case 0x032C: return "NIPPON SMT.CO.,Ltd"
        case 0x032E: return "indoormap"
        case 0x0331: return "3flares Technologies Inc."
        case 0x0333: return "Mul-T-Lock"
        case 0x0335: return "Enlighted Inc"
        case 0x0336: return "GISTIC"
        case 0x0337: return "AJP2 Holdings, LLC"
        case 0x033A: return "Appception, Inc."
        case 0x033C: return "Virtuosys"
        case 0x033E: return "Monitra SA"
        case 0x0343: return "Drekker Development Pty. Ltd."
        case 0x0348: return "Arioneo"
        case 0x034D: return "TASER International, Inc."
        case 0x0352: return "iRiding(Xiamen)Technology Co.,Ltd."
        case 0x0358: return "MagniWare Ltd."
        case 0x035D: return "KYS"
        case 0x0362: return "ON Semiconductor"
        case 0x0366: return "BOLTT Sports technologies Private limited"
        case 0x0370: return "Wazombi Labs Oܠ"
        case 0x0371: return "ORBCOMM"
        case 0x0372: return "Nixie Labs, Inc."
        case 0x0373: return "AppNearMe Ltd"
        case 0x0374: return "Holman Industries"
        case 0x0375: return "Expain AS"
        case 0x0376: return "Electronic Temperature Instruments Ltd"
        case 0x0377: return "Plejd AB"
        case 0x0378: return "Propeller Health"
        case 0x0379: return "Shenzhen iMCO Electronic Technology Co.,Ltd"
        case 0x037A: return "Algoria"
        case 0x037B: return "Apption Labs Inc."
        case 0x037C: return "Cronologics Corporation"
        case 0x037D: return "MICRODIA Ltd."
        case 0x037E: return "lulabytes S.L."
        case 0x037F: return "Nestec S.A."
        case 0x0381: return "Sharp Corporation"
        case 0x0382: return "Precision Outcomes Ltd"
        case 0x0383: return "Kronos Incorporated"
        case 0x0384: return "OCOSMOS Co., Ltd."
        case 0x0385: return "Embedded Electronic Solutions Ltd. dba e2Solutions"
        case 0x0386: return "Aterica Inc."
        case 0x0387: return "BluStor PMC, Inc."
        case 0x0388: return "Kapsch TrafficCom AB"
        case 0x0389: return "ActiveBlu Corporation"
        case 0x038A: return "Kohler Mira Limited"
        case 0x038B: return "Noke"
        case 0x038C: return "Appion Inc."
        case 0x038D: return "Resmed Ltd"
        case 0x038E: return "Crownstone B.V."
        case 0x038F: return "Xiaomi Inc."
        case 0x0390: return "INFOTECH s.r.o."
        case 0x0391: return "Thingsquare AB"
        case 0x0392: return "T&D"
        case 0x0393: return "LAVAZZA S.p.A."
        case 0x0394: return "Netclearance Systems, Inc."
        case 0x0395: return "SDATAWAY"
        case 0x0396: return "BLOKS GmbH"
        case 0x0397: return "LEGO System A/S"
        case 0x0398: return "Thetatronics Ltd"
        case 0x0399: return "Nikon Corporation"
        case 0x039A: return "NeST"
        case 0x039B: return "South Silicon Valley Microelectronics"
        case 0x039C: return "ALE International"
        case 0x039D: return "CareView Communications, Inc."
        case 0x039E: return "SchoolBoard Limited"
        case 0x039F: return "Molex Corporation"
        case 0x03A0: return "IVT Wireless Limited"
        case 0x03A1: return "Alpine Labs LLC"
        case 0x03A2: return "Candura Instruments"
        case 0x03A3: return "SmartMovt Technology Co., Ltd"
        case 0x03A4: return "Token Zero Ltd"
        case 0x03A5: return "ACE CAD Enterprise Co., Ltd. (ACECAD)"
        case 0x03A6: return "Medela, Inc"
        case 0x03A7: return "AeroScout"
        case 0x03A8: return "Esrille Inc."
        case 0x03A9: return "THINKERLY SRL"
        case 0x03AA: return "Exon Sp. z o.o."
        case 0x03AB: return "Meizu Technology Co., Ltd."
        case 0x03AC: return "Smablo LTD"
        case 0x03AD: return "XiQ"
        case 0x03AE: return "Allswell Inc."
        case 0x03AF: return "Comm-N-Sense Corp DBA Verigo"
        case 0x03B0: return "VIBRADORM GmbH"
        case 0x03B1: return "Otodata Wireless Network Inc."
        case 0x03B2: return "Propagation Systems Limited"
        case 0x03B3: return "Midwest Instruments & Controls"
        case 0x03B4: return "Alpha Nodus, inc."
        case 0x03B5: return "petPOMM, Inc"
        case 0x03B6: return "Mattel"
        case 0x03B7: return "Airbly Inc."
        case 0x03B8: return "A-Safe Limited"
        case 0x03B9: return "FREDERIQUE CONSTANT SA"
        case 0x03BA: return "Maxscend Microelectronics Company Limited"
        case 0x03BB: return "Abbott Diabetes Care"
        case 0x03BC: return "ASB Bank Ltd"
        case 0x03BD: return "amadas"
        case 0x03BE: return "Applied Science, Inc."
        case 0x03BF: return "iLumi Solutions Inc."
        case 0x03C0: return "Arch Systems Inc."
        case 0x03C1: return "Ember Technologies, Inc."
        case 0x03C2: return "Snapchat Inc"
        case 0x03C3: return "Casambi Technologies Oy"
        case 0x03C4: return "Pico Technology Inc."
        case 0x03C5: return "St. Jude Medical, Inc."
        case 0x03C6: return "Intricon"
        case 0x03C7: return "Structural Health Systems, Inc."
        case 0x03C8: return "Avvel International"
        case 0x03C9: return "Gallagher Group"
        case 0x03CA: return "In2things Automation Pvt. Ltd."
        case 0x03CB: return "SYSDEV Srl"
        case 0x03CC: return "Vonkil Technologies Ltd"
        case 0x03CD: return "Wynd Technologies, Inc."
        case 0x03CE: return "CONTRINEX S.A."
        case 0x03CF: return "MIRA, Inc."
        case 0x03D0: return "Watteam Ltd"
        case 0x03D1: return "Density Inc."
        case 0x03D2: return "IOT Pot India Private Limited"
        case 0x03D3: return "Sigma Connectivity AB"
        case 0x03D4: return "PEG PEREGO SPA"
        case 0x03D5: return "Wyzelink Systems Inc."
        case 0x03D6: return "Yota Devices LTD"
        case 0x03D7: return "FINSECUR"
        case 0x03D8: return "Zen-Me Labs Ltd"
        case 0x03D9: return "3IWare Co., Ltd."
        case 0x03DA: return "EnOcean GmbH"
        case 0x03DB: return "Instabeat, Inc"
        case 0x03DC: return "Nima Labs"
        case 0x03DD: return "Andreas Stihl AG & Co. KG"
        case 0x03DE: return "Nathan Rhoades LLC"
        case 0x03DF: return "Grob Technologies, LLC"
        case 0x03E0: return "Actions (Zhuhai) Technology Co., Limited"
        case 0x03E1: return "SPD Development Company Ltd"
        case 0x03E2: return "Sensoan Oy"
        case 0x03E3: return "Qualcomm Life Inc"
        case 0x03E4: return "Chip-ing AG"
        case 0x03E5: return "ffly4u"
        case 0x03E6: return "IoT Instruments Oy"
        case 0x03E7: return "TRUE Fitness Technology"
        case 0x03E8: return "Reiner Kartengeraete GmbH & Co. KG."
        case 0x03E9: return "SHENZHEN LEMONJOY TECHNOLOGY CO., LTD."
        case 0x03EA: return "Hello Inc."
        case 0x03EB: return "Evollve Inc."
        case 0x03EC: return "Jigowatts Inc."
        case 0x03ED: return "BASIC MICRO.COM,INC."
        case 0x03EE: return "CUBE TECHNOLOGIES"
        case 0x03EF: return "foolography GmbH"
        case 0x03F0: return "CLINK"
        case 0x03F1: return "Hestan Smart Cooking Inc."
        case 0x03F2: return "WindowMaster A/S"
        case 0x03F3: return "Flowscape AB"
        case 0x03F4: return "PAL Technologies Ltd"
        case 0x03F5: return "WHERE, Inc."
        case 0x03F6: return "Iton Technology Corp."
        case 0x03F7: return "Owl Labs Inc."
        case 0x03F8: return "Rockford Corp."
        case 0x03F9: return "Becon Technologies Co.,Ltd."
        case 0x03FA: return "Vyassoft Technologies Inc"
        case 0x03FB: return "Nox Medical"
        case 0x03FC: return "Kimberly-Clark"
        case 0x03FD: return "Trimble Navigation Ltd."
        case 0x03FE: return "Littelfuse"
        case 0x03FF: return "Withings"
        case 0x0400: return "i-developer IT Beratung UG"
        case 0x0402: return "Sears Holdings Corporation"
        case 0x0403: return "Gantner Electronic GmbH"
        case 0x0404: return "Authomate Inc"
        case 0x0405: return "Vertex International, Inc."
        case 0x0406: return "Airtago"
        case 0x0407: return "Swiss Audio SA"
        case 0x0408: return "ToGetHome Inc."
        case 0x0409: return "AXIS"
        case 0x040A: return "Openmatics"
        case 0x040B: return "Jana Care Inc."
        case 0x040C: return "Senix Corporation"
        case 0x040D: return "NorthStar Battery Company, LLC"
        case 0x040E: return "SKF (U.K.) Limited"
        case 0x040F: return "CO-AX Technology, Inc."
        case 0x0410: return "Fender Musical Instruments"
        case 0x0411: return "Luidia Inc"
        case 0x0412: return "SEFAM"
        case 0x0413: return "Wireless Cables Inc"
        case 0x0414: return "Lightning Protection International Pty Ltd"
        case 0x0415: return "Uber Technologies Inc"
        case 0x0416: return "SODA GmbH"
        case 0x0417: return "Fatigue Science"
        case 0x0418: return "Alpine Electronics Inc."
        case 0x0419: return "Novalogy LTD"
        case 0x041A: return "Friday Labs Limited"
        case 0x041B: return "OrthoAccel Technologies"
        case 0x041C: return "WaterGuru, Inc."
        case 0x041D: return "Benning Elektrotechnik und Elektronik GmbH & Co. KG"
        case 0x041E: return "Dell Computer Corporation"
        case 0x041F: return "Kopin Corporation"
        case 0x0420: return "TecBakery GmbH"
        case 0x0421: return "Backbone Labs, Inc."
        case 0x0422: return "DELSEY SA"
        case 0x0423: return "Chargifi Limited"
        case 0x0424: return "Trainesense Ltd."
        case 0x0425: return "Unify Software and Solutions GmbH & Co. KG"
        case 0x0426: return "Husqvarna AB"
        case 0x0427: return "Focus fleet and fuel management inc"
        case 0x0428: return "SmallLoop, LLC"
        case 0x0429: return "Prolon Inc."
        case 0x042A: return "BD Medical"
        case 0x042B: return "iMicroMed Incorporated"
        case 0x042C: return "Ticto N.V."
        case 0x042D: return "Meshtech AS"
        case 0x042E: return "MemCachier Inc."
        case 0x042F: return "Danfoss A/S"
        case 0x0430: return "SnapStyk Inc."
        case 0x0431: return "Amway Corporation"
        case 0x0432: return "Silk Labs, Inc."
        case 0x0433: return "Pillsy Inc."
        case 0x0434: return "Hatch Baby, Inc."
        case 0x0435: return "Blocks Wearables Ltd."
        case 0x0436: return "Drayson Technologies (Europe) Limited"
        case 0x0437: return "eBest IOT Inc."
        case 0x0438: return "Helvar Ltd"
        case 0x0439: return "Radiance Technologies"
        case 0x043A: return "Nuheara Limited"
        case 0x043B: return "Appside co., ltd."
        case 0x043C: return "DeLaval"
        case 0x043D: return "Coiler Corporation"
        case 0x043E: return "Thermomedics, Inc."
        case 0x043F: return "Tentacle Sync GmbH"
        case 0x0440: return "Valencell, Inc."
        case 0x0441: return "iProtoXi Oy"
        case 0x0442: return "SECOM CO., LTD."
        case 0x0443: return "Tucker International LLC"
        case 0x0444: return "Metanate Limited"
        case 0x0445: return "Kobian Canada Inc."
        case 0x0446: return "NETGEAR, Inc."
        case 0x0447: return "Fabtronics Australia Pty Ltd"
        case 0x0448: return "Grand Centrix GmbH"
        case 0x0449: return "1UP USA.com llc"
        case 0x044A: return "SHIMANO INC."
        case 0x044B: return "Nain Inc."
        case 0x044C: return "LifeStyle Lock, LLC"
        case 0x044D: return "VEGA Grieshaber KG"
        case 0x044E: return "Xtrava Inc."
        case 0x044F: return "TTS Tooltechnic Systems AG & Co. KG"
        case 0x0450: return "Teenage Engineering AB"
        case 0x0451: return "Tunstall Nordic AB"
        case 0x0452: return "Svep Design Center AB"
        case 0x0453: return "GreenPeak Technologies BV"
        case 0x0454: return "Sphinx Electronics GmbH & Co KG"
        case 0x0455: return "Atomation"
        case 0x0456: return "Nemik Consulting Inc"
        case 0x0457: return "RF INNOVATION"
        case 0x0458: return "Mini Solution Co., Ltd."
        case 0x0459: return "Lumenetix, Inc"
        case 0x045A: return "2048450 Ontario Inc"
        case 0x045B: return "SPACEEK LTD"
        case 0x045C: return "Delta T Corporation"
        case 0x045D: return "Boston Scientific Corporation"
        case 0x045E: return "Nuviz, Inc."
        case 0x045F: return "Real Time Automation, Inc."
        case 0x0460: return "Kolibree"
        case 0x0461: return "vhf elektronik GmbH"
        case 0x0462: return "Bonsai Systems GmbH"
        case 0x0463: return "Fathom Systems Inc."
        case 0x0464: return "Bellman & Symfon"
        case 0x0465: return "International Forte Group LLC"
        case 0x0466: return "CycleLabs Solutions inc."
        case 0x0467: return "Codenex Oy"
        case 0x0468: return "Kynesim Ltd"
        case 0x0469: return "Palago AB"
        case 0x046A: return "INSIGMA INC."
        case 0x046B: return "PMD Solutions"
        case 0x046C: return "Qingdao Realtime Technology Co., Ltd."
        case 0x046D: return "BEGA Gantenbrink-Leuchten KG"
        case 0x046E: return "Pambor Ltd."
        case 0x046F: return "Develco Products A/S"
        case 0x0470: return "iDesign s.r.l."
        case 0x0471: return "TiVo Corp"
        case 0x0472: return "Control-J Pty Ltd"
        case 0x0473: return "Steelcase, Inc."
        case 0x0474: return "iApartment co., ltd."
        case 0x0475: return "Icom inc."
        case 0x0476: return "Oxstren Wearable Technologies Private Limited"
        case 0x0477: return "Blue Spark Technologies"
        case 0x0478: return "FarSite Communications Limited"
        case 0x0479: return "mywerk system GmbH"
        case 0x047A: return "Sinosun Technology Co., Ltd."
        case 0x047B: return "MIYOSHI ELECTRONICS CORPORATION"
        case 0x047C: return "POWERMAT LTD"
        case 0x047D: return "Occly LLC"
        case 0x047E: return "OurHub Dev IvS"
        case 0x047F: return "Pro-Mark, Inc."
        case 0x0480: return "Dynometrics Inc."
        case 0x0481: return "Quintrax Limited"
        case 0x0482: return "POS Tuning Udo Vosshenrich GmbH & Co. KG"
        case 0x0483: return "Multi Care Systems B.V."
        case 0x0484: return "Revol Technologies Inc"
        case 0x0485: return "SKIDATA AG"
        case 0x0486: return "DEV TECNOLOGIA INDUSTRIA, COMERCIO E MANUTENCAO DE EQUIPAMENTOS LTDA. - ME"
        case 0x0487: return "Centrica Connected Home"
        case 0x0488: return "Automotive Data Solutions Inc"
        case 0x0489: return "Igarashi Engineering"
        case 0x048A: return "Taelek Oy"
        case 0x048B: return "CP Electronics Limited"
        case 0x048C: return "Vectronix AG"
        case 0x048D: return "S-Labs Sp. z o.o."
        case 0x048E: return "Companion Medical, Inc."
        case 0x048F: return "BlueKitchen GmbH"
        case 0x0490: return "Matting AB"
        case 0x0491: return "SOREX - Wireless Solutions GmbH"
        case 0x0492: return "ADC Technology, Inc."
        case 0x0493: return "Lynxemi Pte Ltd"
        case 0x0494: return "SENNHEISER electronic GmbH & Co. KG"
        case 0x0495: return "LMT Mercer Group, Inc"
        case 0x0496: return "Polymorphic Labs LLC"
        case 0x0497: return "Cochlear Limited"
        case 0x0498: return "METER Group, Inc. USA"
        case 0x0499: return "Ruuvi Innovations Ltd."
        case 0x049A: return "Situne AS"
        case 0x049B: return "nVisti, LLC"
        case 0x049C: return "DyOcean"
        case 0x049D: return "Uhlmann & Zacher GmbH"
        case 0x049E: return "AND!XOR LLC"
        case 0x049F: return "tictote AB"
        case 0x04A0: return "Vypin, LLC"
        case 0x04A1: return "PNI Sensor Corporation"
        case 0x04A2: return "ovrEngineered, LLC"
        case 0x04A3: return "GT-tronics HK Ltd"
        case 0x04A4: return "Herbert Waldmann GmbH & Co. KG"
        case 0x04A5: return "Guangzhou FiiO Electronics Technology Co.,Ltd"
        case 0x04A6: return "Vinetech Co., Ltd"
        case 0x04A7: return "Dallas Logic Corporation"
        case 0x04A8: return "BioTex, Inc."
        case 0x04A9: return "DISCOVERY SOUND TECHNOLOGY, LLC"
        case 0x04AA: return "LINKIO SAS"
        case 0x04AB: return "Harbortronics, Inc."
        case 0x04AC: return "Undagrid B.V."
        case 0x04AD: return "Shure Inc"
        case 0x04AE: return "ERM Electronic Systems LTD"
        case 0x04AF: return "BIOROWER Handelsagentur GmbH"
        case 0x04B0: return "Weba Sport und Med. Artikel GmbH"
        case 0x04B1: return "Kartographers Technologies Pvt. Ltd."
        case 0x04B2: return "The Shadow on the Moon"
        case 0x04B3: return "mobike (Hong Kong) Limited"
        case 0x04B4: return "Inuheat Group AB"
        case 0x04B5: return "Swiftronix AB"
        case 0x04B6: return "Diagnoptics Technologies"
        case 0x04B7: return "Analog Devices, Inc."
        case 0x04B8: return "Soraa Inc."
        case 0x04B9: return "CSR Building Products Limited"
        case 0x04BA: return "Crestron Electronics, Inc."
        case 0x04BB: return "Neatebox Ltd"
        case 0x04BC: return "Draegerwerk AG & Co. KGaA"
        case 0x04BD: return "AlbynMedical"
        case 0x04BE: return "Averos FZCO"
        case 0x04BF: return "VIT Initiative, LLC"
        case 0x04C0: return "Statsports International"
        case 0x04C1: return "Sospitas, s.r.o."
        case 0x04C2: return "Dmet Products Corp."
        case 0x04C3: return "Mantracourt Electronics Limited"
        case 0x04C4: return "TeAM Hutchins AB"
        case 0x04C5: return "Seibert Williams Glass, LLC"
        case 0x04C6: return "Insta GmbH"
        case 0x04C7: return "Svantek Sp. z o.o."
        case 0x04C8: return "Shanghai Flyco Electrical Appliance Co., Ltd."
        case 0x04C9: return "Thornwave Labs Inc"
        case 0x04CA: return "Steiner-Optik GmbH"
        case 0x04CB: return "Novo Nordisk A/S"
        case 0x04CC: return "Enflux Inc."
        case 0x04CD: return "Safetech Products LLC"
        case 0x04CE: return "GOOOLED S.R.L."
        case 0x04CF: return "DOM Sicherheitstechnik GmbH & Co. KG"
        case 0x04D0: return "Olympus Corporation"
        case 0x04D1: return "KTS GmbH"
        case 0x04D2: return "Anloq Technologies Inc."
        case 0x04D3: return "Queercon, Inc"
        case 0x04D4: return "5th Element Ltd"
        case 0x04D5: return "Gooee Limited"
        case 0x04D6: return "LUGLOC LLC"
        case 0x04D7: return "Blincam, Inc."
        case 0x04D8: return "FUJIFILM Corporation"
        case 0x04D9: return "RandMcNally"
        case 0x04DA: return "Franceschi Marina snc"
        case 0x04DB: return "Engineered Audio, LLC."
        case 0x04DC: return "IOTTIVE (OPC) PRIVATE LIMITED"
        case 0x04DD: return "4MOD Technology"
        case 0x04DE: return "Lutron Electronics Co., Inc."
        case 0x04DF: return "Emerson"
        case 0x04E0: return "Guardtec, Inc."
        case 0x04E1: return "REACTEC LIMITED"
        case 0x04E2: return "EllieGrid"
        case 0x04E3: return "Under Armour"
        case 0x04E4: return "Woodenshark"
        case 0x04E5: return "Avack Oy"
        case 0x04E6: return "Smart Solution Technology, Inc."
        case 0x04E7: return "REHABTRONICS INC."
        case 0x04E8: return "STABILO International"
        case 0x04E9: return "Busch Jaeger Elektro GmbH"
        case 0x04EA: return "Pacific Bioscience Laboratories, Inc"
        case 0x04EB: return "Bird Home Automation GmbH"
        case 0x04EC: return "Motorola Solutions"
        case 0x04ED: return "R9 Technology, Inc."
        case 0x04EE: return "Auxivia"
        case 0x04EF: return "DaisyWorks, Inc"
        case 0x04F0: return "Kosi Limited"
        case 0x04F1: return "Theben AG"
        case 0x04F2: return "InDreamer Techsol Private Limited"
        case 0x04F3: return "Cerevast Medical"
        case 0x04F4: return "ZanCompute Inc."
        case 0x04F5: return "Pirelli Tyre S.P.A."
        case 0x04F6: return "McLear Limited"
        case 0x04F7: return "Shenzhen Huiding Technology Co.,Ltd."
        case 0x04F8: return "Convergence Systems Limited"
        case 0x04F9: return "Interactio"
        case 0x04FA: return "Androtec GmbH"
        case 0x04FB: return "Benchmark Drives GmbH & Co. KG"
        case 0x04FC: return "SwingLync L. L. C."
        case 0x04FD: return "Tapkey GmbH"
        case 0x04FE: return "Woosim Systems Inc."
        case 0x04FF: return "Microsemi Corporation"
        case 0x0500: return "Wiliot LTD."
        case 0x0501: return "Polaris IND"
        case 0x0502: return "Specifi-Kali LLC"
        case 0x0503: return "Locoroll, Inc"
        case 0x0504: return "PHYPLUS Inc"
        case 0x0505: return "Inplay Technologies LLC"
        case 0x0506: return "Hager"
        case 0x0507: return "Yellowcog"
        case 0x0508: return "Axes System sp. z o. o."
        case 0x0509: return "myLIFTER Inc."
        case 0x050A: return "Shake-on B.V."
        case 0x050B: return "Vibrissa Inc."
        case 0x050C: return "OSRAM GmbH"
        case 0x050D: return "TRSystems GmbH"
        case 0x050E: return "Yichip Microelectronics (Hangzhou) Co.,Ltd."
        case 0x050F: return "Foundation Engineering LLC"
        case 0x0510: return "UNI-ELECTRONICS, INC."
        case 0x0511: return "Brookfield Equinox LLC"
        case 0x0512: return "Soprod SA"
        case 0x0513: return "9974091 Canada Inc."
        case 0x0514: return "FIBRO GmbH"
        case 0x0515: return "RB Controls Co., Ltd."
        case 0x0516: return "Footmarks"
        case 0x0517: return "Amtronic Sverige AB (formerly Amcore AB)"
        case 0x0518: return "MAMORIO.inc"
        case 0x0519: return "Tyto Life LLC"
        case 0x051A: return "Leica Camera AG"
        case 0x051B: return "Angee Technologies Ltd."
        case 0x051C: return "EDPS"
        case 0x051D: return "OFF Line Co., Ltd."
        case 0x051E: return "Detect Blue Limited"
        case 0x051F: return "Setec Pty Ltd"
        case 0x0520: return "Target Corporation"
        case 0x0521: return "IAI Corporation"
        case 0x0522: return "NS Tech, Inc."
        case 0x0523: return "MTG Co., Ltd."
        case 0x0524: return "Hangzhou iMagic Technology Co., Ltd"
        case 0x0525: return "HONGKONG NANO IC TECHNOLOGIES CO., LIMITED"
        case 0x0526: return "Honeywell International Inc."
        case 0x0527: return "Albrecht JUNG"
        case 0x0528: return "Lunera Lighting Inc."
        case 0x0529: return "Lumen UAB"
        case 0x052A: return "Keynes Controls Ltd"
        case 0x052B: return "Novartis AG"
        case 0x052C: return "Geosatis SA"
        case 0x052D: return "EXFO, Inc."
        case 0x052E: return "LEDVANCE GmbH"
        case 0x052F: return "Center ID Corp."
        case 0x0530: return "Adolene, Inc."
        case 0x0531: return "D&M Holdings Inc."
        case 0x0532: return "CRESCO Wireless, Inc."
        case 0x0533: return "Nura Operations Pty Ltd"
        case 0x0534: return "Frontiergadget, Inc."
        case 0x0535: return "Smart Component Technologies Limited"
        case 0x0536: return "ZTR Control Systems LLC"
        case 0x0537: return "MetaLogics Corporation"
        case 0x0538: return "Medela AG"
        case 0x0539: return "OPPLE Lighting Co., Ltd"
        case 0x053A: return "Savitech Corp.,"
        case 0x053B: return "prodigy"
        case 0x053C: return "Screenovate Technologies Ltd"
        case 0x053D: return "TESA SA"
        case 0x053E: return "CLIM8 LIMITED"
        case 0x053F: return "Silergy Corp"
        case 0x0540: return "SilverPlus, Inc"
        case 0x0541: return "Sharknet srl"
        case 0x0542: return "Mist Systems, Inc."
        case 0x0543: return "MIWA LOCK CO.,Ltd"
        case 0x0544: return "OrthoSensor, Inc."
        case 0x0545: return "Candy Hoover Group s.r.l"
        case 0x0546: return "Apexar Technologies S.A."
        case 0x0547: return "LOGICDATA d.o.o."
        case 0x0548: return "Knick Elektronische Messgeraete GmbH & Co. KG"
        case 0x0549: return "Smart Technologies and Investment Limited"
        case 0x054A: return "Linough Inc."
        case 0x054B: return "Advanced Electronic Designs, Inc."
        case 0x054C: return "Carefree Scott Fetzer Co Inc"
        case 0x054D: return "Sensome"
        case 0x054E: return "FORTRONIK storitve d.o.o."
        case 0x054F: return "Sinnoz"
        case 0x0550: return "Versa Networks, Inc."
        case 0x0551: return "Sylero"
        case 0x0552: return "Avempace SARL"
        case 0x0553: return "Nintendo Co., Ltd."
        case 0x0554: return "National Instruments"
        case 0x0555: return "KROHNE Messtechnik GmbH"
        case 0x0556: return "Otodynamics Ltd"
        case 0x0557: return "Arwin Technology Limited"
        case 0x0558: return "benegear, inc."
        case 0x0559: return "Newcon Optik"
        case 0x055A: return "CANDY HOUSE, Inc."
        case 0x055B: return "FRANKLIN TECHNOLOGY INC"
        case 0x055C: return "Lely"
        case 0x055D: return "Valve Corporation"
        case 0x055E: return "Hekatron Vertriebs GmbH"
        case 0x055F: return "PROTECH S.A.S. DI GIRARDI ANDREA & C."
        case 0x0560: return "Sarita CareTech APS (formerly Sarita CareTech IVS)"
        case 0x0561: return "Finder S.p.A."
        case 0x0562: return "Thalmic Labs Inc."
        case 0x0563: return "Steinel Vertrieb GmbH"
        case 0x0564: return "Beghelli Spa"
        case 0x0565: return "Beijing Smartspace Technologies Inc."
        case 0x0566: return "CORE TRANSPORT TECHNOLOGIES NZ LIMITED"
        case 0x0567: return "Xiamen Everesports Goods Co., Ltd"
        case 0x0568: return "Bodyport Inc."
        case 0x0569: return "Audionics System, INC."
        case 0x056A: return "Flipnavi Co.,Ltd."
        case 0x056B: return "Rion Co., Ltd."
        case 0x056C: return "Long Range Systems, LLC"
        case 0x056D: return "Redmond Industrial Group LLC"
        case 0x056E: return "VIZPIN INC."
        case 0x056F: return "BikeFinder AS"
        case 0x0570: return "Consumer Sleep Solutions LLC"
        case 0x0571: return "PSIKICK, INC."
        case 0x0572: return "AntTail.com"
        case 0x0573: return "Lighting Science Group Corp."
        case 0x0574: return "AFFORDABLE ELECTRONICS INC"
        case 0x0575: return "Integral Memroy Plc"
        case 0x0576: return "Globalstar, Inc."
        case 0x0577: return "True Wearables, Inc."
        case 0x0578: return "Wellington Drive Technologies Ltd"
        case 0x0579: return "Ensemble Tech Private Limited"
        case 0x057A: return "OMNI Remotes"
        case 0x057B: return "Duracell U.S. Operations Inc."
        case 0x057C: return "Toor Technologies LLC"
        case 0x057D: return "Instinct Performance"
        case 0x057E: return "Beco, Inc"
        case 0x057F: return "Scuf Gaming International, LLC"
        case 0x0580: return "ARANZ Medical Limited"
        case 0x0581: return "LYS TECHNOLOGIES LTD"
        case 0x0582: return "Breakwall Analytics, LLC"
        case 0x0583: return "Code Blue Communications"
        case 0x0584: return "Gira Giersiepen GmbH & Co. KG"
        case 0x0585: return "Hearing Lab Technology"
        case 0x0586: return "LEGRAND"
        case 0x0587: return "Derichs GmbH"
        case 0x0588: return "ALT-TEKNIK LLC"
        case 0x0589: return "Star Technologies"
        case 0x058A: return "START TODAY CO.,LTD."
        case 0x058B: return "Maxim Integrated Products"
        case 0x058C: return "MERCK Kommanditgesellschaft auf Aktien"
        case 0x058D: return "Jungheinrich Aktiengesellschaft"
        case 0x058E: return "Oculus VR, LLC"
        case 0x058F: return "HENDON SEMICONDUCTORS PTY LTD"
        case 0x0590: return "Pur3 Ltd"
        case 0x0591: return "Viasat Group S.p.A."
        case 0x0592: return "IZITHERM"
        case 0x0593: return "Spaulding Clinical Research"
        case 0x0594: return "Kohler Company"
        case 0x0595: return "Inor Process AB"
        case 0x0596: return "My Smart Blinds"
        case 0x0597: return "RadioPulse Inc"
        case 0x0598: return "rapitag GmbH"
        case 0x0599: return "Lazlo326, LLC."
        case 0x059A: return "Teledyne Lecroy, Inc."
        case 0x059B: return "Dataflow Systems Limited"
        case 0x059C: return "Macrogiga Electronics"
        case 0x059D: return "Tandem Diabetes Care"
        case 0x059E: return "Polycom, Inc."
        case 0x059F: return "Fisher & Paykel Healthcare"
        case 0x05A0: return "RCP Software Oy"
        case 0x05A1: return "Shanghai Xiaoyi Technology Co.,Ltd."
        case 0x05A2: return "ADHERIUM(NZ) LIMITED"
        case 0x05A3: return "Axiomware Systems Incorporated"
        case 0x05A4: return "O. E. M. Controls, Inc."
        case 0x05A5: return "Kiiroo BV"
        case 0x05A6: return "Telecon Mobile Limited"
        case 0x05A7: return "Sonos Inc"
        case 0x05A8: return "Tom Allebrandi Consulting"
        case 0x05A9: return "Monidor"
        case 0x05AA: return "Tramex Limited"
        case 0x05AB: return "Nofence AS"
        case 0x05AC: return "GoerTek Dynaudio Co., Ltd."
        case 0x05AD: return "INIA"
        case 0x05AE: return "CARMATE MFG.CO.,LTD"
        case 0x05AF: return "ONvocal"
        case 0x05B0: return "NewTec GmbH"
        case 0x05B1: return "Medallion Instrumentation Systems"
        case 0x05B2: return "CAREL INDUSTRIES S.P.A."
        case 0x05B3: return "Parabit Systems, Inc."
        case 0x05B4: return "White Horse Scientific ltd"
        case 0x05B5: return "verisilicon"
        case 0x05B6: return "Elecs Industry Co.,Ltd."
        case 0x05B7: return "Beijing Pinecone Electronics Co.,Ltd."
        case 0x05B8: return "Ambystoma Labs Inc."
        case 0x05B9: return "Suzhou Pairlink Network Technology"
        case 0x05BA: return "igloohome"
        case 0x05BB: return "Oxford Metrics plc"
        case 0x05BC: return "Leviton Mfg. Co., Inc."
        case 0x05BD: return "ULC Robotics Inc."
        case 0x05BE: return "RFID Global by Softwork SrL"
        case 0x05BF: return "Real-World-Systems Corporation"
        case 0x05C0: return "Nalu Medical, Inc."
        case 0x05C1: return "P.I.Engineering"
        case 0x05C2: return "Grote Industries"
        case 0x05C3: return "Runtime, Inc."
        case 0x05C4: return "Codecoup sp. z o.o. sp. k."
        case 0x05C5: return "SELVE GmbH & Co. KG"
        case 0x05C6: return "Smart Animal Training Systems, LLC"
        case 0x05C7: return "Lippert Components, INC"
        case 0x05C8: return "SOMFY SAS"
        case 0x05C9: return "TBS Electronics B.V."
        case 0x05CA: return "MHL Custom Inc"
        case 0x05CB: return "LucentWear LLC"
        case 0x05CC: return "WATTS ELECTRONICS"
        case 0x05CD: return "RJ Brands LLC"
        case 0x05CE: return "V-ZUG Ltd"
        case 0x05CF: return "Biowatch SA"
        case 0x05D0: return "Anova Applied Electronics"
        case 0x05D1: return "Lindab AB"
        case 0x05D2: return "frogblue TECHNOLOGY GmbH"
        case 0x05D3: return "Acurable Limited"
        case 0x05D4: return "LAMPLIGHT Co., Ltd."
        case 0x05D5: return "TEGAM, Inc."
        case 0x05D6: return "Zhuhai Jieli technology Co.,Ltd"
        case 0x05D7: return "modum.io AG"
        case 0x05D8: return "Farm Jenny LLC"
        case 0x05D9: return "Toyo Electronics Corporation"
        case 0x05DA: return "Applied Neural Research Corp"
        case 0x05DB: return "Avid Identification Systems, Inc."
        case 0x05DC: return "Petronics Inc."
        case 0x05DD: return "essentim GmbH"
        case 0x05DE: return "QT Medical INC."
        case 0x05DF: return "VIRTUALCLINIC.DIRECT LIMITED"
        case 0x05E0: return "Viper Design LLC"
        case 0x05E1: return "Human, Incorporated"
        case 0x05E2: return "stAPPtronics GmbH"
        case 0x05E3: return "Elemental Machines, Inc."
        case 0x05E4: return "Taiyo Yuden Co., Ltd"
        case 0x05E5: return "INEO ENERGY& SYSTEMS"
        case 0x05E6: return "Motion Instruments Inc."
        case 0x05E7: return "PressurePro"
        case 0x05E8: return "COWBOY"
        case 0x05E9: return "iconmobile GmbH"
        case 0x05EA: return "ACS-Control-System GmbH"
        case 0x05EB: return "Bayerische Motoren Werke AG"
        case 0x05EC: return "Gycom Svenska AB"
        case 0x05ED: return "Fuji Xerox Co., Ltd"
        case 0x05EE: return "Glide Inc."
        case 0x05EF: return "SIKOM AS"
        case 0x05F0: return "beken"
        case 0x05F1: return "The Linux Foundation"
        case 0x05F2: return "Try and E CO.,LTD."
        case 0x05F3: return "SeeScan"
        case 0x05F4: return "Clearity, LLC"
        case 0x05F5: return "GS TAG"
        case 0x05F6: return "DPTechnics"
        case 0x05F7: return "TRACMO, INC."
        case 0x05F8: return "Anki Inc."
        case 0x05F9: return "Hagleitner Hygiene International GmbH"
        case 0x05FA: return "Konami Sports Life Co., Ltd."
        case 0x05FB: return "Arblet Inc."
        case 0x05FC: return "Masbando GmbH"
        case 0x05FD: return "Innoseis"
        case 0x05FE: return "Niko"
        case 0x05FF: return "Wellnomics Ltd"
        case 0x0600: return "iRobot Corporation"
        case 0x0601: return "Schrader Electronics"
        case 0x0602: return "Geberit International AG"
        case 0x0603: return "Fourth Evolution Inc"
        case 0x0604: return "Cell2Jack LLC"
        case 0x0605: return "FMW electronic Futterer u. Maier-Wolf OHG"
        case 0x0606: return "John Deere"
        case 0x0607: return "Rookery Technology Ltd"
        case 0x0608: return "KeySafe-Cloud"
        case 0x0609: return "BUCHI Labortechnik AG"
        case 0x060A: return "IQAir AG"
        case 0x060B: return "Triax Technologies Inc"
        case 0x060C: return "Vuzix Corporation"
        case 0x060D: return "TDK Corporation"
        case 0x060E: return "Blueair AB"
        case 0x060F: return "Signify Netherlands"
        case 0x0610: return "ADH GUARDIAN USA LLC"
        case 0x0611: return "Beurer GmbH"
        case 0x0612: return "Playfinity AS"
        case 0x0613: return "Hans Dinslage GmbH"
        case 0x0614: return "OnAsset Intelligence, Inc."
        case 0x0615: return "INTER ACTION Corporation"
        case 0x0616: return "OS42 UG (haftungsbeschraenkt)"
        case 0x0617: return "WIZCONNECTED COMPANY LIMITED"
        case 0x0618: return "Audio-Technica Corporation"
        case 0x0619: return "Six Guys Labs, s.r.o."
        case 0x061A: return "R.W. Beckett Corporation"
        case 0x061B: return "silex technology, inc."
        case 0x061C: return "Univations Limited"
        case 0x061D: return "SENS Innovation ApS"
        case 0x061E: return "Diamond Kinetics, Inc."
        case 0x061F: return "Phrame Inc."
        case 0x0620: return "Forciot Oy"
        case 0x0621: return "Noordung d.o.o."
        case 0x0622: return "Beam Labs, LLC"
        case 0x0623: return "Philadelphia Scientific (U.K.) Limited"
        case 0x0624: return "Biovotion AG"
        case 0x0625: return "Square Panda, Inc."
        case 0x0626: return "Amplifico"
        case 0x0627: return "WEG S.A."
        case 0x0628: return "Ensto Oy"
        case 0x0629: return "PHONEPE PVT LTD"
        case 0x062A: return "Lunatico Astronomia SL"
        case 0x062B: return "MinebeaMitsumi Inc."
        case 0x062C: return "ASPion GmbH"
        case 0x062D: return "Vossloh-Schwabe Deutschland GmbH"
        case 0x062E: return "Procept"
        case 0x062F: return "ONKYO Corporation"
        case 0x0630: return "Asthrea D.O.O."
        case 0x0631: return "Fortiori Design LLC"
        case 0x0632: return "Hugo Muller GmbH & Co KG"
        case 0x0633: return "Wangi Lai PLT"
        case 0x0634: return "Fanstel Corp"
        case 0x0635: return "Crookwood"
        case 0x0636: return "ELECTRONICA INTEGRAL DE SONIDO S.A."
        case 0x0637: return "GiP Innovation Tools GmbH"
        case 0x0638: return "LX SOLUTIONS PTY LIMITED"
        case 0x0639: return "Shenzhen Minew Technologies Co., Ltd."
        case 0x063A: return "Prolojik Limited"
        case 0x063B: return "Kromek Group Plc"
        case 0x063C: return "Contec Medical Systems Co., Ltd."
        case 0x063D: return "Xradio Technology Co.,Ltd."
        case 0x063E: return "The Indoor Lab, LLC"
        case 0x063F: return "LDL TECHNOLOGY"
        case 0x0640: return "Parkifi"
        case 0x0641: return "Revenue Collection Systems FRANCE SAS"
        case 0x0642: return "Bluetrum Technology Co.,Ltd"
        case 0x0643: return "makita corporation"
        case 0x0644: return "Apogee Instruments"
        case 0x0645: return "BM3"
        case 0x0646: return "SGV Group Holding GmbH & Co. KG"
        case 0x0647: return "MED-EL"
        case 0x0648: return "Ultune Technologies"
        case 0x0649: return "Ryeex Technology Co.,Ltd."
        case 0x064A: return "Open Research Institute, Inc."
        case 0x064B: return "Scale-Tec, Ltd"
        case 0x064C: return "Zumtobel Group AG"
        case 0x064D: return "iLOQ Oy"
        case 0x064E: return "KRUXWorks Technologies Private Limited"
        case 0x064F: return "Digital Matter Pty Ltd"
        case 0x0650: return "Coravin, Inc."
        case 0x0651: return "Stasis Labs, Inc."
        case 0x0652: return "ITZ Innovations- und Technologiezentrum GmbH"
        case 0x0653: return "Meggitt SA"
        case 0x0654: return "Ledlenser GmbH & Co. KG"
        case 0x0655: return "Renishaw PLC"
        case 0x0656: return "ZhuHai AdvanPro Technology Company Limited"
        case 0x0657: return "Meshtronix Limited"
        case 0x0658: return "Payex Norge AS"
        case 0x0659: return "UnSeen Technologies Oy"
        case 0x065A: return "Zound Industries International AB"
        case 0x065B: return "Sesam Solutions BV"
        case 0x065C: return "PixArt Imaging Inc."
        case 0x065D: return "Panduit Corp."
        case 0x065E: return "Alo AB"
        case 0x065F: return "Ricoh Company Ltd"
        case 0x0660: return "RTC Industries, Inc."
        case 0x0661: return "Mode Lighting Limited"
        case 0x0662: return "Particle Industries, Inc."
        case 0x0663: return "Advanced Telemetry Systems, Inc."
        case 0x0664: return "RHA TECHNOLOGIES LTD"
        case 0x0665: return "Pure International Limited"
        case 0x0666: return "WTO Werkzeug-Einrichtungen GmbH"
        case 0x0667: return "Spark Technology Labs Inc."
        case 0x0668: return "Bleb Technology srl"
        case 0x0669: return "Livanova USA, Inc."
        case 0x066A: return "Brady Worldwide Inc."
        case 0x066B: return "DewertOkin GmbH"
        case 0x066C: return "Ztove ApS"
        case 0x066D: return "Venso EcoSolutions AB"
        case 0x066E: return "Eurotronik Kranj d.o.o."
        case 0x066F: return "Hug Technology Ltd"
        case 0x0670: return "Gema Switzerland GmbH"
        case 0x0671: return "Buzz Products Ltd."
        case 0x0672: return "Kopi"
        case 0x0673: return "Innova Ideas Limited"
        case 0x0674: return "BeSpoon"
        case 0x0675: return "Deco Enterprises, Inc."
        case 0x0676: return "Expai Solutions Private Limited"
        case 0x0677: return "Innovation First, Inc."
        case 0x0678: return "SABIK Offshore GmbH"
        case 0x0679: return "4iiii Innovations Inc."
        case 0x067A: return "The Energy Conservatory, Inc."
        case 0x067B: return "I.FARM, INC."
        case 0x067C: return "Tile, Inc."
        case 0x067D: return "Form Athletica Inc."
        case 0x067E: return "MbientLab Inc"
        case 0x067F: return "NETGRID S.N.C. DI BISSOLI MATTEO, CAMPOREALE SIMONE, TOGNETTI FEDERICO"
        case 0x0680: return "Mannkind Corporation"
        case 0x0681: return "Trade FIDES a.s."
        case 0x0682: return "Photron Limited"
        case 0x0683: return "Eltako GmbH"
        case 0x0684: return "Dermalapps, LLC"
        case 0x0685: return "Greenwald Industries"
        case 0x0686: return "inQs Co., Ltd."
        case 0x0687: return "Cherry GmbH"
        case 0x0688: return "Amsted Digital Solutions Inc."
        case 0x0689: return "Tacx b.v."
        case 0x068A: return "Raytac Corporation"
        case 0x068B: return "Jiangsu Teranovo Tech Co., Ltd."
        case 0x068C: return "Changzhou Sound Dragon Electronics and Acoustics Co., Ltd"
        case 0x068D: return "JetBeep Inc."
        case 0x068E: return "Razer Inc."
        case 0x068F: return "JRM Group Limited"
        case 0x0690: return "Eccrine Systems, Inc."
        case 0x0691: return "Curie Point AB"
        case 0x0692: return "Georg Fischer AG"
        case 0x0693: return "Hach - Danaher"
        case 0x0694: return "T&A Laboratories LLC"
        case 0x0695: return "Koki Holdings Co., Ltd."
        case 0x0696: return "Gunakar Private Limited"
        case 0x0697: return "Stemco Products Inc"
        case 0x0698: return "Wood IT Security, LLC"
        case 0x0699: return "RandomLab SAS"
        case 0x069A: return "Adero, Inc. (formerly as TrackR, Inc.)"
        case 0x069B: return "Dragonchip Limited"
        case 0x069C: return "Noomi AB"
        case 0x069D: return "Vakaros LLC"
        case 0x069E: return "Delta Electronics, Inc."
        case 0x069F: return "FlowMotion Technologies AS"
        case 0x06A0: return "OBIQ Location Technology Inc."
        case 0x06A1: return "Cardo Systems, Ltd"
        case 0x06A2: return "Globalworx GmbH"
        case 0x06A3: return "Nymbus, LLC"
        case 0x06A4: return "Sanyo Techno Solutions Tottori Co., Ltd."
        case 0x06A5: return "TEKZITEL PTY LTD"
        case 0x06A6: return "Roambee Corporation"
        case 0x06A7: return "Chipsea Technologies (ShenZhen) Corp."
        case 0x06A8: return "GD Midea Air-Conditioning Equipment Co., Ltd."
        case 0x06A9: return "Soundmax Electronics Limited"
        case 0x06AA: return "Produal Oy"
        case 0x06AB: return "HMS Industrial Networks AB"
        case 0x06AC: return "Ingchips Technology Co., Ltd."
        case 0x06AD: return "InnovaSea Systems Inc."
        case 0x06AE: return "SenseQ Inc."
        case 0x06AF: return "Shoof Technologies"
        case 0x06B0: return "BRK Brands, Inc."
        case 0x06B1: return "SimpliSafe, Inc."
        case 0x06B2: return "Tussock Innovation 2013 Limited"
        case 0x06B3: return "The Hablab ApS"
        case 0x06B4: return "Sencilion Oy"
        case 0x06B5: return "Wabilogic Ltd."
        case 0x06B6: return "Sociometric Solutions, Inc."
        case 0x06B7: return "iCOGNIZE GmbH"
        case 0x06B8: return "ShadeCraft, Inc"
        case 0x06B9: return "Beflex Inc."
        case 0x06BA: return "Beaconzone Ltd"
        case 0x06BB: return "Leaftronix Analogic Solutions Private Limited"
        case 0x06BC: return "TWS Srl"
        case 0x06BD: return "ABB Oy"
        case 0x06BE: return "HitSeed Oy"
        case 0x06BF: return "Delcom Products Inc."
        case 0x06C0: return "CAME S.p.A."
        case 0x06C1: return "Alarm.com Holdings, Inc"
        case 0x06C2: return "Measurlogic Inc."
        case 0x06C3: return "King I Electronics.Co.,Ltd"
        case 0x06C4: return "Dream Labs GmbH"
        case 0x06C5: return "Urban Compass, Inc"
        case 0x06C6: return "Simm Tronic Limited"
        case 0x06C7: return "Somatix Inc"
        case 0x06C8: return "Storz & Bickel GmbH & Co. KG"
        case 0x06C9: return "MYLAPS B.V."
        case 0x06CA: return "Shenzhen Zhongguang Infotech Technology Development Co., Ltd"
        case 0x06CB: return "Dyeware, LLC"
        case 0x06CC: return "Dongguan SmartAction Technology Co.,Ltd."
        case 0x06CD: return "DIG Corporation"
        case 0x06CE: return "FIOR & GENTZ"
        case 0x06CF: return "Belparts N.V."
        case 0x06D0: return "Etekcity Corporation"
        case 0x06D1: return "Meyer Sound Laboratories, Incorporated"
        case 0x06D2: return "CeoTronics AG"
        case 0x06D3: return "TriTeq Lock and Security, LLC"
        case 0x06D4: return "DYNAKODE TECHNOLOGY PRIVATE LIMITED"
        case 0x06D5: return "Sensirion AG"
        case 0x06D6: return "JCT Healthcare Pty Ltd"
        case 0x06D7: return "FUBA Automotive Electronics GmbH"
        case 0x06D8: return "AW Company"
        case 0x06D9: return "Shanghai Mountain View Silicon Co.,Ltd."
        case 0x06DA: return "Zliide Technologies ApS"
        case 0x06DB: return "Automatic Labs, Inc."
        case 0x06DC: return "Industrial Network Controls, LLC"
        case 0x06DD: return "Intellithings Ltd."
        case 0x06DE: return "Navcast, Inc."
        case 0x06DF: return "Hubbell Lighting, Inc."
        case 0x06E1: return "Milestone AV Technologies LLC"
        case 0x06E2: return "Alango Technologies Ltd"
        case 0x06E3: return "Spinlock Ltd"
        case 0x06E4: return "Aluna"
        case 0x06E5: return "OPTEX CO.,LTD."
        case 0x06E6: return "NIHON DENGYO KOUSAKU"
        case 0x06E7: return "VELUX A/S"
        case 0x06E8: return "Almendo Technologies GmbH"
        case 0x06E9: return "Zmartfun Electronics, Inc."
        case 0x06EA: return "SafeLine Sweden AB"
        case 0x06EB: return "Houston Radar LLC"
        case 0x06EC: return "Sigur"
        case 0x06ED: return "J Neades Ltd"
        case 0x06EE: return "Avantis Systems Limited"
        case 0x06EF: return "ALCARE Co., Ltd."
        case 0x06F0: return "Chargy Technologies, SL"
        case 0x06F1: return "Shibutani Co., Ltd."
        case 0x06F2: return "Trapper Data AB"
        case 0x06F3: return "Alfred International Inc."
        case 0x06F4: return "Near Field Solutions Ltd"
        case 0x06F5: return "Vigil Technologies Inc."
        case 0x06F6: return "Vitulo Plus BV"
        case 0x06F7: return "WILKA Schliesstechnik GmbH"
        case 0x06F8: return "BodyPlus Technology Co.,Ltd"
        case 0x06F9: return "happybrush GmbH"
        case 0x06FA: return "Enequi AB"
        case 0x06FB: return "Sartorius AG"
        case 0x06FC: return "Tom Communication Industrial Co.,Ltd."
        case 0x06FD: return "ESS Embedded System Solutions Inc."
        case 0x06FE: return "Mahr GmbH"
        case 0x06FF: return "Redpine Signals Inc"
        case 0x0700: return "TraqFreq LLC"
        case 0x0701: return "PAFERS TECH"
        case 0x0703: return "Beijing Jingdong Century Trading Co., Ltd."
        case 0x0704: return "JBX Designs Inc."
        case 0x0705: return "AB Electrolux"
        case 0x0706: return "Wernher von Braun Center for ASdvanced Research"
        case 0x0707: return "Essity Hygiene and Health Aktiebolag"
        case 0x0708: return "Be Interactive Co., Ltd"
        case 0x0709: return "Carewear Corp."
        case 0x070B: return "Element Products, Inc."
        case 0x070C: return "Beijing Winner Microelectronics Co.,Ltd"
        case 0x070D: return "SmartSnugg Pty Ltd"
        case 0x070E: return "FiveCo Sarl"
        case 0x070F: return "California Things Inc."
        case 0x0710: return "Audiodo AB"
        case 0x0711: return "ABAX AS"
        case 0x0712: return "Bull Group Company Limited"
        case 0x0713: return "Respiri Limited"
        case 0x0714: return "MindPeace Safety LLC"
        case 0x0715: return "Vgyan Solutions"
        case 0x0716: return "Altonics"
        case 0x0717: return "iQsquare BV"
        case 0x0718: return "IDIBAIX enginneering"
        case 0x0719: return "ECSG"
        case 0x071A: return "REVSMART WEARABLE HK CO LTD"
        case 0x071B: return "Precor"
        case 0x071C: return "F5 Sports, Inc"
        case 0x071D: return "exoTIC Systems"
        case 0x071E: return "DONGGUAN HELE ELECTRONICS CO., LTD"
        case 0x071F: return "Dongguan Liesheng Electronic Co.Ltd"
        case 0x0720: return "Oculeve, Inc."
        case 0x0721: return "Clover Network, Inc."
        case 0x0722: return "Xiamen Eholder Electronics Co.Ltd"
        case 0x0723: return "Ford Motor Company"
        case 0x0724: return "Guangzhou SuperSound Information Technology Co.,Ltd"
        case 0x0725: return "Tedee Sp. z o.o."
        case 0x0726: return "PHC Corporation"
        case 0x0727: return "STALKIT AS"
        case 0x0728: return "Eli Lilly and Company"
        case 0x0729: return "SwaraLink Technologies"
        case 0x072A: return "JMR embedded systems GmbH"
        case 0x072B: return "Bitkey Inc."
        case 0x072C: return "GWA Hygiene GmbH"
        case 0x072D: return "Safera Oy"
        case 0x072E: return "Open Platform Systems LLC"
        case 0x072F: return "OnePlus Electronics (Shenzhen) Co., Ltd."
        case 0x0730: return "Wildlife Acoustics, Inc."
        case 0x0731: return "ABLIC Inc."
        case 0x0732: return "Dairy Tech, Inc."
        case 0x0733: return "Iguanavation, Inc."
        case 0x0734: return "DiUS Computing Pty Ltd"
        case 0x0735: return "UpRight Technologies LTD"
        case 0x0736: return "FrancisFund, LLC"
        case 0x0737: return "LLC Navitek"
        case 0x0738: return "Glass Security Pte Ltd"
        case 0x0739: return "Jiangsu Qinheng Co., Ltd."
        case 0x073A: return "Chandler Systems Inc."
        case 0x073B: return "Fantini Cosmi s.p.a."
        case 0x073C: return "Acubit ApS"
        case 0x073D: return "Beijing Hao Heng Tian Tech Co., Ltd."
        case 0x073E: return "Bluepack S.R.L."
        case 0x073F: return "Beijing Unisoc Technologies Co., Ltd."
        case 0x0740: return "HITIQ LIMITED"
        case 0x0741: return "MAC SRL"
        case 0x0742: return "DML LLC"
        case 0x0743: return "Sanofi"
        case 0x0744: return "SOCOMEC"
        case 0x0745: return "WIZNOVA, Inc."
        case 0x0746: return "Seitec Elektronik GmbH"
        case 0x0747: return "OR Technologies Pty Ltd"
        case 0x0748: return "GuangZhou KuGou Computer Technology Co.Ltd"
        case 0x0749: return "DIAODIAO (Beijing) Technology Co., Ltd."
        case 0x074A: return "Illusory Studios LLC"
        case 0x074B: return "Sarvavid Software Solutions LLP"
        case 0x074C: return "iopool s.a."
        case 0x074D: return "Amtech Systems, LLC"
        case 0x074E: return "EAGLE DETECTION SA"
        case 0x074F: return "MEDIATECH S.R.L."
        case 0x0750: return "Hamilton Professional Services of Canada Incorporated"
        case 0x0751: return "Changsha JEMO IC Design Co.,Ltd"
        case 0x0752: return "Elatec GmbH"
        case 0x0753: return "JLG Industries, Inc."
        case 0x0754: return "Michael Parkin"
        case 0x0755: return "Brother Industries, Ltd"
        case 0x0756: return "Lumens For Less, Inc"
        case 0x0757: return "ELA Innovation"
        case 0x0758: return "umanSense AB"
        case 0x0759: return "Shanghai InGeek Cyber Security Co., Ltd."
        case 0x075A: return "HARMAN CO.,LTD."
        case 0x075B: return "Smart Sensor Devices AB"
        case 0x075C: return "Antitronics Inc."
        case 0x075D: return "RHOMBUS SYSTEMS, INC."
        case 0x075E: return "Katerra Inc."
        case 0x075F: return "Remote Solution Co., LTD."
        case 0x0760: return "Vimar SpA"
        case 0x0761: return "Mantis Tech LLC"
        case 0x0762: return "TerOpta Ltd"
        case 0x0763: return "PIKOLIN S.L."
        case 0x0764: return "WWZN Information Technology Company Limited"
        case 0x0765: return "Voxx International"
        case 0x0766: return "ART AND PROGRAM, INC."
        case 0x0767: return "NITTO DENKO ASIA TECHNICAL CENTRE PTE. LTD."
        case 0x0768: return "Peloton Interactive Inc."
        case 0x0769: return "Force Impact Technologies"
        case 0x076A: return "Dmac Mobile Developments, LLC"
        case 0x076B: return "Engineered Medical Technologies"
        case 0x076C: return "Noodle Technology inc"
        case 0x076D: return "Graesslin GmbH"
        case 0x076E: return "WuQi technologies, Inc."
        case 0x076F: return "Successful Endeavours Pty Ltd"
        case 0x0770: return "InnoCon Medical ApS"
        case 0x0771: return "Corvex Connected Safety"
        case 0x0772: return "Thirdwayv Inc."
        case 0x0773: return "Echoflex Solutions Inc."
        case 0x0774: return "C-MAX Asia Limited"
        case 0x0775: return "4eBusiness GmbH"
        case 0x0776: return "Cyber Transport Control GmbH"
        case 0x0777: return "Cue"
        case 0x0778: return "KOAMTAC INC."
        case 0x0779: return "Loopshore Oy"
        case 0x077A: return "Niruha Systems Private Limited"
        case 0x077B: return "AmaterZ, Inc."
        case 0x077C: return "radius co., ltd."
        case 0x077D: return "Sensority, s.r.o."
        case 0x077E: return "Sparkage Inc."
        case 0x077F: return "Glenview Software Corporation"
        case 0x0780: return "Finch Technologies Ltd."
        case 0x0781: return "Qingping Technology (Beijing) Co., Ltd."
        case 0x0782: return "DeviceDrive AS"
        case 0x0783: return "ESEMBER LIMITED LIABILITY COMPANY"
        case 0x0784: return "audifon GmbH & Co. KG"
        case 0x0785: return "O2 Micro, Inc."
        case 0x0786: return "HLP Controls Pty Limited"
        case 0x0787: return "Pangaea Solution"
        case 0x0788: return "BubblyNet, LLC"
        case 0x078A: return "The Wildflower Foundation"
        case 0x078B: return "Optikam Tech Inc."
        case 0x078C: return "MINIBREW HOLDING B.V"
        case 0x078D: return "Cybex GmbH"
        case 0x078E: return "FUJIMIC NIIGATA, INC."
        case 0x078F: return "Hanna Instruments, Inc."
        case 0x0790: return "KOMPAN A/S"
        case 0x0791: return "Scosche Industries, Inc."
        case 0x0792: return "Provo Craft"
        case 0x0793: return "AEV spol. s r.o."
        case 0x0794: return "The Coca-Cola Company"
        case 0x0795: return "GASTEC CORPORATION"
        case 0x0796: return "StarLeaf Ltd"
        case 0x0797: return "Water-i.d. GmbH"
        case 0x0798: return "HoloKit, Inc."
        case 0x0799: return "PlantChoir Inc."
        case 0x079A: return "GuangDong Oppo Mobile Telecommunications Corp., Ltd."
        case 0x079B: return "CST ELECTRONICS (PROPRIETARY) LIMITED"
        case 0x079C: return "Sky UK Limited"
        case 0x079D: return "Digibale Pty Ltd"
        case 0x079E: return "Smartloxx GmbH"
        case 0x079F: return "Pune Scientific LLP"
        case 0x07A0: return "Regent Beleuchtungskorper AG"
        case 0x07A1: return "Apollo Neuroscience, Inc."
        case 0x07A2: return "Roku, Inc."
        case 0x07A3: return "Comcast Cable"
        case 0x07A4: return "Xiamen Mage Information Technology Co., Ltd."
        case 0x07A5: return "RAB Lighting, Inc."
        case 0x07A6: return "Musen Connect, Inc."
        case 0x07A7: return "Zume, Inc."
        case 0x07A8: return "conbee GmbH"
        case 0x07A9: return "Bruel & Kjaer Sound & Vibration"
        case 0x07AA: return "The Kroger Co."
        case 0x07AB: return "Granite River Solutions, Inc."
        case 0x07AC: return "LoupeDeck Oy"
        case 0x07AD: return "New H3C Technologies Co.,Ltd"
        case 0x07AE: return "Aurea Solucoes Tecnologicas Ltda."
        case 0x07AF: return "Hong Kong Bouffalo Lab Limited"
        case 0x07B0: return "GV Concepts Inc."
        case 0x07B1: return "Thomas Dynamics, LLC"
        case 0x07B2: return "Moeco IOT Inc."
        case 0x07B3: return "2N TELEKOMUNIKACE a.s."
        case 0x07B4: return "Hormann KG Antriebstechnik"
        case 0x07B5: return "CRONO CHIP, S.L."
        case 0x07B6: return "Soundbrenner Limited"
        case 0x07B7: return "ETABLISSEMENTS GEORGES RENAULT"
        case 0x07B8: return "iSwip"
        case 0x07B9: return "Epona Biotec Limited"
        case 0x07BA: return "Battery-Biz Inc."
        case 0x07BB: return "EPIC S.R.L."
        case 0x07BC: return "KD CIRCUITS LLC"
        case 0x07BD: return "Genedrive Diagnostics Ltd"
        case 0x07BE: return "Axentia Technologies AB"
        case 0x07BF: return "REGULA Ltd."
        case 0x07C0: return "Biral AG"
        case 0x07C1: return "A.W. Chesterton Company"
        case 0x07C2: return "Radinn AB"
        case 0x07C3: return "CIMTechniques, Inc."
        case 0x07C4: return "Johnson Health Tech NA"
        default:     return nil
        }
    }
    
}
