name: Bug report
description: Create a report to help us improve nRF Mesh.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: type
    attributes:
      label: Where do you suspect the issue?
      description: Is it a UI bug in nRF Mesh or an issue in the mesh library?
      options:
        - Issue in mesh library, e.g. packets being dropped
        - Mesh related issue in nRF Mesh, e.g. sending vendor messages doesn't work
        - UI issue in nRF Mesh app, e.g. button is not clickable
        - Other
      default: 0
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our product are you running?
      options:
        - 4.3.2 (latest)
        - 4.3.0 or 4.3.1
        - 4.2.0
        - 4.1.0
        - 4.0.x
        - 3.2.0
      default: 0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Describe the issue, expected and actual result.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: text
  - type: markdown
    attributes:
      value: |
        If you need to attach a file, create the issue and add it as a comment.
